// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Advantage = { };

var AnimistForce = { };

var Blessing = { };

var Cantrip = { };

var Condition = { };

var IncreaseSkill = { };

var Culture = {
  IncreaseSkill: IncreaseSkill
};

var Curse = { };

var DerivedCharacteristic = { };

var Disadvantage = { };

var DominationRitual = { };

var ElvenMagicalSong = { };

var EquipmentPackage = { };

var ExperienceLevel = { };

var FocusRule = { };

var GeodeRitual = { };

var Item = { };

var LiturgicalChant = { };

var MagicalDance = { };

var MagicalMelody = { };

var MagicalTradition = { };

var Messages = { };

var OptionalRule = { };

var PactCategory = { };

var Category = { };

var Patron = {
  Category: Category
};

var NameBySex = { };

var IncreaseSkillList = { };

var CantripSelection = { };

var CombatTechniqueSelection = { };

var CurseSelection = { };

var LanguageScriptSelection = { };

var SkillSpecializationSelection = { };

var SkillSelection = { };

var TerrainKnowledgeSelection = { };

var Options = {
  CantripSelection: CantripSelection,
  CombatTechniqueSelection: CombatTechniqueSelection,
  CurseSelection: CurseSelection,
  LanguageScriptSelection: LanguageScriptSelection,
  SkillSpecializationSelection: SkillSpecializationSelection,
  SkillSelection: SkillSelection,
  TerrainKnowledgeSelection: TerrainKnowledgeSelection
};

var Variant = { };

var Profession = {
  NameBySex: NameBySex,
  IncreaseSkillList: IncreaseSkillList,
  Options: Options,
  Variant: Variant
};

var Publication = { };

var Die = { };

var Variant$1 = { };

var Race = {
  Die: Die,
  Variant: Variant$1
};

var RogueSpell = { };

var SkillGroup = { };

var SpecialAbility = { };

var Spell = { };

var State = { };

var ZibiljaRitual = { };

var SourceRef = /* alias */0;

var Erratum = /* alias */0;

var Prerequisites = /* alias */0;

var Skill = /* alias */0;

var SelectOption = /* alias */0;

var Attribute = /* alias */0;

var BlessedTradition = /* alias */0;

var CombatTechnique = /* alias */0;

exports.SourceRef = SourceRef;
exports.Erratum = Erratum;
exports.Prerequisites = Prerequisites;
exports.Skill = Skill;
exports.SelectOption = SelectOption;
exports.Advantage = Advantage;
exports.AnimistForce = AnimistForce;
exports.Attribute = Attribute;
exports.BlessedTradition = BlessedTradition;
exports.Blessing = Blessing;
exports.Cantrip = Cantrip;
exports.CombatTechnique = CombatTechnique;
exports.Condition = Condition;
exports.Culture = Culture;
exports.Curse = Curse;
exports.DerivedCharacteristic = DerivedCharacteristic;
exports.Disadvantage = Disadvantage;
exports.DominationRitual = DominationRitual;
exports.ElvenMagicalSong = ElvenMagicalSong;
exports.EquipmentPackage = EquipmentPackage;
exports.ExperienceLevel = ExperienceLevel;
exports.FocusRule = FocusRule;
exports.GeodeRitual = GeodeRitual;
exports.Item = Item;
exports.LiturgicalChant = LiturgicalChant;
exports.MagicalDance = MagicalDance;
exports.MagicalMelody = MagicalMelody;
exports.MagicalTradition = MagicalTradition;
exports.Messages = Messages;
exports.OptionalRule = OptionalRule;
exports.PactCategory = PactCategory;
exports.Patron = Patron;
exports.Profession = Profession;
exports.Publication = Publication;
exports.Race = Race;
exports.RogueSpell = RogueSpell;
exports.SkillGroup = SkillGroup;
exports.SpecialAbility = SpecialAbility;
exports.Spell = Spell;
exports.State = State;
exports.ZibiljaRitual = ZibiljaRitual;
/* No side effect */
