/* eslint-disable jsdoc/require-jsdoc */
/* eslint-disable @typescript-eslint/no-namespace */
import { createSelector } from "@reduxjs/toolkit"
import { All, GetById } from "../../shared/domain/getTypes.ts"
import {
  selectDynamicAdvancedCombatSpecialAbilities,
  selectDynamicAdvancedKarmaSpecialAbilities,
  selectDynamicAdvancedMagicalSpecialAbilities,
  selectDynamicAdvancedSkillSpecialAbilities,
  selectDynamicAdvantages,
  selectDynamicAncestorGlyphs,
  selectDynamicAnimistPowers,
  selectDynamicArcaneOrbEnchantments,
  selectDynamicAttireEnchantments,
  selectDynamicAttributes,
  selectDynamicBlessedTraditions,
  selectDynamicBlessings,
  selectDynamicBowlEnchantments,
  selectDynamicBrawlingSpecialAbilities,
  selectDynamicCantrips,
  selectDynamicCauldronEnchantments,
  selectDynamicCeremonialItemSpecialAbilities,
  selectDynamicCeremonies,
  selectDynamicChronicleEnchantments,
  selectDynamicCloseCombatTechniques,
  selectDynamicCombatSpecialAbilities,
  selectDynamicCombatStyleSpecialAbilities,
  selectDynamicCommandSpecialAbilities,
  selectDynamicCurses,
  selectDynamicDaggerRituals,
  selectDynamicDisadvantages,
  selectDynamicDominationRituals,
  selectDynamicElvenMagicalSongs,
  selectDynamicFamiliarSpecialAbilities,
  selectDynamicFatePointSexSpecialAbilities,
  selectDynamicFatePointSpecialAbilities,
  selectDynamicFocusRules,
  selectDynamicFoolsHatEnchantments,
  selectDynamicGeneralSpecialAbilities,
  selectDynamicGeodeRituals,
  selectDynamicInstrumentEnchantments,
  selectDynamicJesterTricks,
  selectDynamicKarmaSpecialAbilities,
  selectDynamicKrallenkettenzauber,
  selectDynamicLiturgicalChants,
  selectDynamicLiturgicalStyleSpecialAbilities,
  selectDynamicLycantropicGifts,
  selectDynamicMagicStyleSpecialAbilities,
  selectDynamicMagicalDances,
  selectDynamicMagicalMelodies,
  selectDynamicMagicalRunes,
  selectDynamicMagicalSigns,
  selectDynamicMagicalSpecialAbilities,
  selectDynamicMagicalTraditions,
  selectDynamicOptionalRules,
  selectDynamicOrbEnchantments,
  selectDynamicPactGifts,
  selectDynamicProtectiveWardingCircleSpecialAbilities,
  selectDynamicRangedCombatTechniques,
  selectDynamicRingEnchantments,
  selectDynamicRituals,
  selectDynamicSermons,
  selectDynamicSexSpecialAbilities,
  selectDynamicSickleRituals,
  selectDynamicSikaryanDrainSpecialAbilities,
  selectDynamicSkillStyleSpecialAbilities,
  selectDynamicSkills,
  selectDynamicSpellSwordEnchantments,
  selectDynamicSpells,
  selectDynamicStaffEnchantments,
  selectDynamicStates,
  selectDynamicToyEnchantments,
  selectDynamicTrinkhornzauber,
  selectDynamicVampiricGifts,
  selectDynamicVisions,
  selectDynamicWandEnchantments,
  selectDynamicWeaponEnchantments,
  selectDynamicZibiljaRituals,
} from "../slices/characterSlice.ts"
import { selectDatabase } from "../slices/databaseSlice.ts"

// prettier-ignore
export namespace SelectGetById {
  export namespace Static {
    export const AdvancedCombatSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.AdvancedCombatSpecialAbility => id => database.advancedCombatSpecialAbilities[id])
    export const AdvancedKarmaSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.AdvancedKarmaSpecialAbility => id => database.advancedKarmaSpecialAbilities[id])
    export const AdvancedMagicalSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.AdvancedMagicalSpecialAbility => id => database.advancedMagicalSpecialAbilities[id])
    export const AdvancedSkillSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.AdvancedSkillSpecialAbility => id => database.advancedSkillSpecialAbilities[id])
    export const Advantage = createSelector(selectDatabase, (database): GetById.Static.Advantage => id => database.advantages[id])
    export const Ammunition = createSelector(selectDatabase, (database): GetById.Static.Ammunition => id => database.ammunition[id])
    export const AncestorGlyph = createSelector(selectDatabase, (database): GetById.Static.AncestorGlyph => id => database.ancestorGlyphs[id])
    export const AnimalCare = createSelector(selectDatabase, (database): GetById.Static.AnimalCare => id => database.animalCare[id])
    export const AnimalDisease = createSelector(selectDatabase, (database): GetById.Static.AnimalDisease => id => database.animalDiseases[id])
    export const Animal = createSelector(selectDatabase, (database): GetById.Static.Animal => id => database.animals[id])
    export const AnimalShapePath = createSelector(selectDatabase, (database): GetById.Static.AnimalShapePath => id => database.animalShapePaths[id])
    export const AnimalShape = createSelector(selectDatabase, (database): GetById.Static.AnimalShape => id => database.animalShapes[id])
    export const AnimalShapeSize = createSelector(selectDatabase, (database): GetById.Static.AnimalShapeSize => id => database.animalShapeSizes[id])
    export const AnimalType = createSelector(selectDatabase, (database): GetById.Static.AnimalType => id => database.animalTypes[id])
    export const AnimistPower = createSelector(selectDatabase, (database): GetById.Static.AnimistPower => id => database.animistPowers[id])
    export const Tribe = createSelector(selectDatabase, (database): GetById.Static.Tribe => id => database.animistPowerTribes[id])
    export const ArcaneBardTradition = createSelector(selectDatabase, (database): GetById.Static.ArcaneBardTradition => id => database.arcaneBardTraditions[id])
    export const ArcaneDancerTradition = createSelector(selectDatabase, (database): GetById.Static.ArcaneDancerTradition => id => database.arcaneDancerTraditions[id])
    export const ArcaneOrbEnchantment = createSelector(selectDatabase, (database): GetById.Static.ArcaneOrbEnchantment => id => database.arcaneOrbEnchantments[id])
    export const Armor = createSelector(selectDatabase, (database): GetById.Static.Armor => id => database.armors[id])
    export const ArmorType = createSelector(selectDatabase, (database): GetById.Static.ArmorType => id => database.armorTypes[id])
    export const Aspect = createSelector(selectDatabase, (database): GetById.Static.Aspect => id => database.aspects[id])
    export const AttireEnchantment = createSelector(selectDatabase, (database): GetById.Static.AttireEnchantment => id => database.attireEnchantments[id])
    export const Attribute = createSelector(selectDatabase, (database): GetById.Static.Attribute => id => database.attributes[id])
    export const BandageOrRemedy = createSelector(selectDatabase, (database): GetById.Static.BandageOrRemedy => id => database.bandagesAndRemedies[id])
    export const BlessedTradition = createSelector(selectDatabase, (database): GetById.Static.BlessedTradition => id => database.blessedTraditions[id])
    export const Blessing = createSelector(selectDatabase, (database): GetById.Static.Blessing => id => database.blessings[id])
    export const Book = createSelector(selectDatabase, (database): GetById.Static.Book => id => database.books[id])
    export const BowlEnchantment = createSelector(selectDatabase, (database): GetById.Static.BowlEnchantment => id => database.bowlEnchantments[id])
    export const BrawlingSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.BrawlingSpecialAbility => id => database.brawlingSpecialAbilities[id])
    export const Brew = createSelector(selectDatabase, (database): GetById.Static.Brew => id => database.brews[id])
    export const Cantrip = createSelector(selectDatabase, (database): GetById.Static.Cantrip => id => database.cantrips[id])
    export const CauldronEnchantment = createSelector(selectDatabase, (database): GetById.Static.CauldronEnchantment => id => database.cauldronEnchantments[id])
    export const CeremonialItem = createSelector(selectDatabase, (database): GetById.Static.CeremonialItem => id => database.ceremonialItems[id])
    export const CeremonialItemSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.CeremonialItemSpecialAbility => id => database.ceremonialItemSpecialAbilities[id])
    export const Ceremony = createSelector(selectDatabase, (database): GetById.Static.Ceremony => id => database.ceremonies[id])
    export const ChronicleEnchantment = createSelector(selectDatabase, (database): GetById.Static.ChronicleEnchantment => id => database.chronicleEnchantments[id])
    export const CloseCombatTechnique = createSelector(selectDatabase, (database): GetById.Static.CloseCombatTechnique => id => database.closeCombatTechniques[id])
    export const Clothes = createSelector(selectDatabase, (database): GetById.Static.Clothes => id => database.clothes[id])
    export const CombatSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.CombatSpecialAbility => id => database.combatSpecialAbilities[id])
    export const CombatStyleSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.CombatStyleSpecialAbility => id => database.combatStyleSpecialAbilities[id])
    export const CommandSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.CommandSpecialAbility => id => database.commandSpecialAbilities[id])
    export const Condition = createSelector(selectDatabase, (database): GetById.Static.Condition => id => database.conditions[id])
    export const Container = createSelector(selectDatabase, (database): GetById.Static.Container => id => database.containers[id])
    export const Continent = createSelector(selectDatabase, (database): GetById.Static.Continent => id => database.continents[id])
    export const CoreRule = createSelector(selectDatabase, (database): GetById.Static.CoreRule => id => database.coreRules[id])
    export const Culture = createSelector(selectDatabase, (database): GetById.Static.Culture => id => database.cultures[id])
    export const Curse = createSelector(selectDatabase, (database): GetById.Static.Curse => id => database.curses[id])
    export const DaggerRitual = createSelector(selectDatabase, (database): GetById.Static.DaggerRitual => id => database.daggerRituals[id])
    export const DerivedCharacteristic = createSelector(selectDatabase, (database): GetById.Static.DerivedCharacteristic => id => database.derivedCharacteristics[id])
    export const Disadvantage = createSelector(selectDatabase, (database): GetById.Static.Disadvantage => id => database.disadvantages[id])
    export const Disease = createSelector(selectDatabase, (database): GetById.Static.Disease => id => database.diseases[id])
    export const DominationRitual = createSelector(selectDatabase, (database): GetById.Static.DominationRitual => id => database.dominationRituals[id])
    export const Element = createSelector(selectDatabase, (database): GetById.Static.Element => id => database.elements[id])
    export const Elixir = createSelector(selectDatabase, (database): GetById.Static.Elixir => id => database.elixirs[id])
    export const ElvenMagicalSong = createSelector(selectDatabase, (database): GetById.Static.ElvenMagicalSong => id => database.elvenMagicalSongs[id])
    export const EquipmentOfBlessedOnes = createSelector(selectDatabase, (database): GetById.Static.EquipmentOfBlessedOnes => id => database.equipmentOfBlessedOnes[id])
    export const EquipmentPackage = createSelector(selectDatabase, (database): GetById.Static.EquipmentPackage => id => database.equipmentPackages[id])
    export const ExperienceLevel = createSelector(selectDatabase, (database): GetById.Static.ExperienceLevel => id => database.experienceLevels[id])
    export const EyeColor = createSelector(selectDatabase, (database): GetById.Static.EyeColor => id => database.eyeColors[id])
    export const FamiliarSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.FamiliarSpecialAbility => id => database.familiarSpecialAbilities[id])
    export const FamiliarsTrick = createSelector(selectDatabase, (database): GetById.Static.FamiliarsTrick => id => database.familiarsTricks[id])
    export const FatePointSexSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.FatePointSexSpecialAbility => id => database.fatePointSexSpecialAbilities[id])
    export const FatePointSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.FatePointSpecialAbility => id => database.fatePointSpecialAbilities[id])
    export const FocusRule = createSelector(selectDatabase, (database): GetById.Static.FocusRule => id => database.focusRules[id])
    export const Subject = createSelector(selectDatabase, (database): GetById.Static.Subject => id => database.focusRuleSubjects[id])
    export const FoolsHatEnchantment = createSelector(selectDatabase, (database): GetById.Static.FoolsHatEnchantment => id => database.foolsHatEnchantments[id])
    export const GemOrPreciousStone = createSelector(selectDatabase, (database): GetById.Static.GemOrPreciousStone => id => database.gemsAndPreciousStones[id])
    export const GeneralSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.GeneralSpecialAbility => id => database.generalSpecialAbilities[id])
    export const GeodeRitual = createSelector(selectDatabase, (database): GetById.Static.GeodeRitual => id => database.geodeRituals[id])
    export const HairColor = createSelector(selectDatabase, (database): GetById.Static.HairColor => id => database.hairColors[id])
    export const IlluminationLightSource = createSelector(selectDatabase, (database): GetById.Static.IlluminationLightSource => id => database.illuminationLightSources[id])
    export const IlluminationRefillsOrSupplies = createSelector(selectDatabase, (database): GetById.Static.IlluminationRefillsOrSupplies => id => database.illuminationRefillsAndSupplies[id])
    export const InstrumentEnchantment = createSelector(selectDatabase, (database): GetById.Static.InstrumentEnchantment => id => database.instrumentEnchantments[id])
    export const JesterTrick = createSelector(selectDatabase, (database): GetById.Static.JesterTrick => id => database.jesterTricks[id])
    export const Jewelry = createSelector(selectDatabase, (database): GetById.Static.Jewelry => id => database.jewelry[id])
    export const KarmaSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.KarmaSpecialAbility => id => database.karmaSpecialAbilities[id])
    export const Kirchenpraegung = createSelector(selectDatabase, (database): GetById.Static.Kirchenpraegung => id => database.kirchenpraegungen[id])
    export const Krallenkettenzauber = createSelector(selectDatabase, (database): GetById.Static.Krallenkettenzauber => id => database.krallenkettenzauber[id])
    export const Language = createSelector(selectDatabase, (database): GetById.Static.Language => id => database.languages[id])
    export const Curriculum = createSelector(selectDatabase, (database): GetById.Static.Curriculum => id => database.lessonsCurricula[id])
    export const Guideline = createSelector(selectDatabase, (database): GetById.Static.Guideline => id => database.lessonsGuidelines[id])
    export const Liebesspielzeug = createSelector(selectDatabase, (database): GetById.Static.Liebesspielzeug => id => database.liebesspielzeug[id])
    export const LiturgicalChant = createSelector(selectDatabase, (database): GetById.Static.LiturgicalChant => id => database.liturgicalChants[id])
    export const LiturgicalStyleSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.LiturgicalStyleSpecialAbility => id => database.liturgicalStyleSpecialAbilities[id])
    export const Locale = createSelector(selectDatabase, (database): GetById.Static.Locale => id => database.locales[id])
    export const LuxuryGood = createSelector(selectDatabase, (database): GetById.Static.LuxuryGood => id => database.luxuryGoods[id])
    export const LycantropicGift = createSelector(selectDatabase, (database): GetById.Static.LycantropicGift => id => database.lycantropicGifts[id])
    export const MagicalArtifact = createSelector(selectDatabase, (database): GetById.Static.MagicalArtifact => id => database.magicalArtifacts[id])
    export const MagicalDance = createSelector(selectDatabase, (database): GetById.Static.MagicalDance => id => database.magicalDances[id])
    export const MagicalMelody = createSelector(selectDatabase, (database): GetById.Static.MagicalMelody => id => database.magicalMelodies[id])
    export const MagicalRune = createSelector(selectDatabase, (database): GetById.Static.MagicalRune => id => database.magicalRunes[id])
    export const MagicalSign = createSelector(selectDatabase, (database): GetById.Static.MagicalSign => id => database.magicalSigns[id])
    export const MagicalSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.MagicalSpecialAbility => id => database.magicalSpecialAbilities[id])
    export const MagicalTradition = createSelector(selectDatabase, (database): GetById.Static.MagicalTradition => id => database.magicalTraditions[id])
    export const MagicStyleSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.MagicStyleSpecialAbility => id => database.magicStyleSpecialAbilities[id])
    export const MetaCondition = createSelector(selectDatabase, (database): GetById.Static.MetaCondition => id => database.metaConditions[id])
    export const MusicalInstrument = createSelector(selectDatabase, (database): GetById.Static.MusicalInstrument => id => database.musicalInstruments[id])
    export const OptionalRule = createSelector(selectDatabase, (database): GetById.Static.OptionalRule => id => database.optionalRules[id])
    export const OrbEnchantment = createSelector(selectDatabase, (database): GetById.Static.OrbEnchantment => id => database.orbEnchantments[id])
    export const OrienteeringAid = createSelector(selectDatabase, (database): GetById.Static.OrienteeringAid => id => database.orienteeringAids[id])
    export const PactCategory = createSelector(selectDatabase, (database): GetById.Static.PactCategory => id => database.pactCategories[id])
    export const PactGift = createSelector(selectDatabase, (database): GetById.Static.PactGift => id => database.pactGifts[id])
    export const PatronCategory = createSelector(selectDatabase, (database): GetById.Static.PatronCategory => id => database.patronCategories[id])
    export const Patron = createSelector(selectDatabase, (database): GetById.Static.Patron => id => database.patrons[id])
    export const PersonalityTrait = createSelector(selectDatabase, (database): GetById.Static.PersonalityTrait => id => database.personalityTraits[id])
    export const Poison = createSelector(selectDatabase, (database): GetById.Static.Poison => id => database.poisons[id])
    export const Profession = createSelector(selectDatabase, (database): GetById.Static.Profession => id => database.professions[id])
    export const Property = createSelector(selectDatabase, (database): GetById.Static.Property => id => database.properties[id])
    export const ProtectiveWardingCircleSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.ProtectiveWardingCircleSpecialAbility => id => database.protectiveWardingCircleSpecialAbilities[id])
    export const Publication = createSelector(selectDatabase, (database): GetById.Static.Publication => id => database.publications[id])
    export const Race = createSelector(selectDatabase, (database): GetById.Static.Race => id => database.races[id])
    export const RangedCombatTechnique = createSelector(selectDatabase, (database): GetById.Static.RangedCombatTechnique => id => database.rangedCombatTechniques[id])
    export const Reach = createSelector(selectDatabase, (database): GetById.Static.Reach => id => database.reaches[id])
    export const Region = createSelector(selectDatabase, (database): GetById.Static.Region => id => database.regions[id])
    export const RingEnchantment = createSelector(selectDatabase, (database): GetById.Static.RingEnchantment => id => database.ringEnchantments[id])
    export const Ritual = createSelector(selectDatabase, (database): GetById.Static.Ritual => id => database.rituals[id])
    export const RopeOrChain = createSelector(selectDatabase, (database): GetById.Static.RopeOrChain => id => database.ropesAndChains[id])
    export const Script = createSelector(selectDatabase, (database): GetById.Static.Script => id => database.scripts[id])
    export const Sermon = createSelector(selectDatabase, (database): GetById.Static.Sermon => id => database.sermons[id])
    export const Service = createSelector(selectDatabase, (database): GetById.Static.Service => id => database.services[id])
    export const SexPractice = createSelector(selectDatabase, (database): GetById.Static.SexPractice => id => database.sexPractices[id])
    export const SexSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.SexSpecialAbility => id => database.sexSpecialAbilities[id])
    export const SickleRitual = createSelector(selectDatabase, (database): GetById.Static.SickleRitual => id => database.sickleRituals[id])
    export const SikaryanDrainSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.SikaryanDrainSpecialAbility => id => database.sikaryanDrainSpecialAbilities[id])
    export const SkillGroup = createSelector(selectDatabase, (database): GetById.Static.SkillGroup => id => database.skillGroups[id])
    export const SkillModificationLevel = createSelector(selectDatabase, (database): GetById.Static.SkillModificationLevel => id => database.skillModificationLevels[id])
    export const Skill = createSelector(selectDatabase, (database): GetById.Static.Skill => id => database.skills[id])
    export const SkillStyleSpecialAbility = createSelector(selectDatabase, (database): GetById.Static.SkillStyleSpecialAbility => id => database.skillStyleSpecialAbilities[id])
    export const SocialStatus = createSelector(selectDatabase, (database): GetById.Static.SocialStatus => id => database.socialStatuses[id])
    export const Spell = createSelector(selectDatabase, (database): GetById.Static.Spell => id => database.spells[id])
    export const SpellSwordEnchantment = createSelector(selectDatabase, (database): GetById.Static.SpellSwordEnchantment => id => database.spellSwordEnchantments[id])
    export const StaffEnchantment = createSelector(selectDatabase, (database): GetById.Static.StaffEnchantment => id => database.staffEnchantments[id])
    export const State = createSelector(selectDatabase, (database): GetById.Static.State => id => database.states[id])
    export const Stationary = createSelector(selectDatabase, (database): GetById.Static.Stationary => id => database.stationary[id])
    export const Talisman = createSelector(selectDatabase, (database): GetById.Static.Talisman => id => database.talismans[id])
    export const TargetCategory = createSelector(selectDatabase, (database): GetById.Static.TargetCategory => id => database.targetCategories[id])
    export const ThievesTool = createSelector(selectDatabase, (database): GetById.Static.ThievesTool => id => database.thievesTools[id])
    export const ToolOfTheTrade = createSelector(selectDatabase, (database): GetById.Static.ToolOfTheTrade => id => database.toolsOfTheTrade[id])
    export const ToyEnchantment = createSelector(selectDatabase, (database): GetById.Static.ToyEnchantment => id => database.toyEnchantments[id])
    export const TradeSecret = createSelector(selectDatabase, (database): GetById.Static.TradeSecret => id => database.tradeSecrets[id])
    export const TravelGearOrTool = createSelector(selectDatabase, (database): GetById.Static.TravelGearOrTool => id => database.travelGearAndTools[id])
    export const Trinkhornzauber = createSelector(selectDatabase, (database): GetById.Static.Trinkhornzauber => id => database.trinkhornzauber[id])
    export const UI = createSelector(selectDatabase, (database): GetById.Static.UI => id => database.ui[id])
    export const VampiricGift = createSelector(selectDatabase, (database): GetById.Static.VampiricGift => id => database.vampiricGifts[id])
    export const Vehicle = createSelector(selectDatabase, (database): GetById.Static.Vehicle => id => database.vehicles[id])
    export const Vision = createSelector(selectDatabase, (database): GetById.Static.Vision => id => database.visions[id])
    export const WandEnchantment = createSelector(selectDatabase, (database): GetById.Static.WandEnchantment => id => database.wandEnchantments[id])
    export const WeaponAccessory = createSelector(selectDatabase, (database): GetById.Static.WeaponAccessory => id => database.weaponAccessories[id])
    export const WeaponEnchantment = createSelector(selectDatabase, (database): GetById.Static.WeaponEnchantment => id => database.weaponEnchantments[id])
    export const Weapon = createSelector(selectDatabase, (database): GetById.Static.Weapon => id => database.weapons[id])
    export const ZibiljaRitual = createSelector(selectDatabase, (database): GetById.Static.ZibiljaRitual => id => database.zibiljaRituals[id])
  }

  export namespace Dynamic {
    export const AdvancedCombatSpecialAbility = createSelector(selectDynamicAdvancedCombatSpecialAbilities, (dynamicAdvancedCombatSpecialAbilities): GetById.Dynamic.AdvancedCombatSpecialAbility => id => dynamicAdvancedCombatSpecialAbilities?.[id])
    export const AdvancedKarmaSpecialAbility = createSelector(selectDynamicAdvancedKarmaSpecialAbilities, (dynamicAdvancedKarmaSpecialAbilities): GetById.Dynamic.AdvancedKarmaSpecialAbility => id => dynamicAdvancedKarmaSpecialAbilities?.[id])
    export const AdvancedMagicalSpecialAbility = createSelector(selectDynamicAdvancedMagicalSpecialAbilities, (dynamicAdvancedMagicalSpecialAbilities): GetById.Dynamic.AdvancedMagicalSpecialAbility => id => dynamicAdvancedMagicalSpecialAbilities?.[id])
    export const AdvancedSkillSpecialAbility = createSelector(selectDynamicAdvancedSkillSpecialAbilities, (dynamicAdvancedSkillSpecialAbilities): GetById.Dynamic.AdvancedSkillSpecialAbility => id => dynamicAdvancedSkillSpecialAbilities?.[id])
    export const Advantage = createSelector(selectDynamicAdvantages, (dynamicAdvantages): GetById.Dynamic.Advantage => id => dynamicAdvantages?.[id])
    // export const Ammunition = createSelector(selectDynamicAmmunition, (dynamicAmmunition): GetById.Dynamic.Ammunition => id => dynamicAmmunition?.[id])
    export const AncestorGlyph = createSelector(selectDynamicAncestorGlyphs, (dynamicAncestorGlyphs): GetById.Dynamic.AncestorGlyph => id => dynamicAncestorGlyphs?.[id])
    // export const AnimalCare = createSelector(selectDynamicAnimalCare, (dynamicAnimalCare): GetById.Dynamic.AnimalCare => id => dynamicAnimalCare?.[id])
    export const AnimistPower = createSelector(selectDynamicAnimistPowers, (dynamicAnimistPowers): GetById.Dynamic.AnimistPower => id => dynamicAnimistPowers?.[id])
    export const ArcaneOrbEnchantment = createSelector(selectDynamicArcaneOrbEnchantments, (dynamicArcaneOrbEnchantments): GetById.Dynamic.ArcaneOrbEnchantment => id => dynamicArcaneOrbEnchantments?.[id])
    // export const Armor = createSelector(selectDynamicArmors, (dynamicArmors): GetById.Dynamic.Armor => id => dynamicArmors?.[id])
    export const AttireEnchantment = createSelector(selectDynamicAttireEnchantments, (dynamicAttireEnchantments): GetById.Dynamic.AttireEnchantment => id => dynamicAttireEnchantments?.[id])
    export const Attribute = createSelector(selectDynamicAttributes, (dynamicAttributes): GetById.Dynamic.Attribute => id => dynamicAttributes?.[id])
    // export const BandageOrRemedy = createSelector(selectDynamicBandagesAndRemedies, (dynamicBandagesAndRemedies): GetById.Dynamic.BandageOrRemedy => id => dynamicBandagesAndRemedies?.[id])
    export const BlessedTradition = createSelector(selectDynamicBlessedTraditions, (dynamicBlessedTraditions): GetById.Dynamic.BlessedTradition => id => dynamicBlessedTraditions?.[id])
    export const Blessing = createSelector(selectDynamicBlessings, (dynamicBlessings): GetById.Dynamic.Blessing => id => dynamicBlessings?.[id])
    // export const Book = createSelector(selectDynamicBooks, (dynamicBooks): GetById.Dynamic.Book => id => dynamicBooks?.[id])
    export const BowlEnchantment = createSelector(selectDynamicBowlEnchantments, (dynamicBowlEnchantments): GetById.Dynamic.BowlEnchantment => id => dynamicBowlEnchantments?.[id])
    export const BrawlingSpecialAbility = createSelector(selectDynamicBrawlingSpecialAbilities, (dynamicBrawlingSpecialAbilities): GetById.Dynamic.BrawlingSpecialAbility => id => dynamicBrawlingSpecialAbilities?.[id])
    export const Cantrip = createSelector(selectDynamicCantrips, (dynamicCantrips): GetById.Dynamic.Cantrip => id => dynamicCantrips?.[id])
    export const CauldronEnchantment = createSelector(selectDynamicCauldronEnchantments, (dynamicCauldronEnchantments): GetById.Dynamic.CauldronEnchantment => id => dynamicCauldronEnchantments?.[id])
    // export const CeremonialItem = createSelector(selectDynamicCeremonialItems, (dynamicCeremonialItems): GetById.Dynamic.CeremonialItem => id => dynamicCeremonialItems?.[id])
    export const CeremonialItemSpecialAbility = createSelector(selectDynamicCeremonialItemSpecialAbilities, (dynamicCeremonialItemSpecialAbilities): GetById.Dynamic.CeremonialItemSpecialAbility => id => dynamicCeremonialItemSpecialAbilities?.[id])
    export const Ceremony = createSelector(selectDynamicCeremonies, (dynamicCeremonies): GetById.Dynamic.Ceremony => id => dynamicCeremonies?.[id])
    export const ChronicleEnchantment = createSelector(selectDynamicChronicleEnchantments, (dynamicChronicleEnchantments): GetById.Dynamic.ChronicleEnchantment => id => dynamicChronicleEnchantments?.[id])
    export const CloseCombatTechnique = createSelector(selectDynamicCloseCombatTechniques, (dynamicCloseCombatTechniques): GetById.Dynamic.CloseCombatTechnique => id => dynamicCloseCombatTechniques?.[id])
    // export const Clothes = createSelector(selectDynamicClothes, (dynamicClothes): GetById.Dynamic.Clothes => id => dynamicClothes?.[id])
    export const CombatSpecialAbility = createSelector(selectDynamicCombatSpecialAbilities, (dynamicCombatSpecialAbilities): GetById.Dynamic.CombatSpecialAbility => id => dynamicCombatSpecialAbilities?.[id])
    export const CombatStyleSpecialAbility = createSelector(selectDynamicCombatStyleSpecialAbilities, (dynamicCombatStyleSpecialAbilities): GetById.Dynamic.CombatStyleSpecialAbility => id => dynamicCombatStyleSpecialAbilities?.[id])
    export const CommandSpecialAbility = createSelector(selectDynamicCommandSpecialAbilities, (dynamicCommandSpecialAbilities): GetById.Dynamic.CommandSpecialAbility => id => dynamicCommandSpecialAbilities?.[id])
    // export const Condition = createSelector(selectDynamicConditions, (dynamicConditions): GetById.Dynamic.Condition => id => dynamicConditions?.[id])
    // export const Container = createSelector(selectDynamicContainers, (dynamicContainers): GetById.Dynamic.Container => id => dynamicContainers?.[id])
    export const Curse = createSelector(selectDynamicCurses, (dynamicCurses): GetById.Dynamic.Curse => id => dynamicCurses?.[id])
    export const DaggerRitual = createSelector(selectDynamicDaggerRituals, (dynamicDaggerRituals): GetById.Dynamic.DaggerRitual => id => dynamicDaggerRituals?.[id])
    // export const DerivedCharacteristic = createSelector(selectDynamicDerivedCharacteristics, (dynamicDerivedCharacteristics): GetById.Dynamic.DerivedCharacteristic => id => dynamicDerivedCharacteristics?.[id])
    export const Disadvantage = createSelector(selectDynamicDisadvantages, (dynamicDisadvantages): GetById.Dynamic.Disadvantage => id => dynamicDisadvantages?.[id])
    // export const Disease = createSelector(selectDynamicDiseases, (dynamicDiseases): GetById.Dynamic.Disease => id => dynamicDiseases?.[id])
    export const DominationRitual = createSelector(selectDynamicDominationRituals, (dynamicDominationRituals): GetById.Dynamic.DominationRitual => id => dynamicDominationRituals?.[id])
    // export const Elixir = createSelector(selectDynamicElixirs, (dynamicElixirs): GetById.Dynamic.Elixir => id => dynamicElixirs?.[id])
    export const ElvenMagicalSong = createSelector(selectDynamicElvenMagicalSongs, (dynamicElvenMagicalSongs): GetById.Dynamic.ElvenMagicalSong => id => dynamicElvenMagicalSongs?.[id])
    // export const EquipmentOfBlessedOnes = createSelector(selectDynamicEquipmentOfBlessedOnes, (dynamicEquipmentOfBlessedOnes): GetById.Dynamic.EquipmentOfBlessedOnes => id => dynamicEquipmentOfBlessedOnes?.[id])
    export const FamiliarSpecialAbility = createSelector(selectDynamicFamiliarSpecialAbilities, (dynamicFamiliarSpecialAbilities): GetById.Dynamic.FamiliarSpecialAbility => id => dynamicFamiliarSpecialAbilities?.[id])
    // export const FamiliarsTrick = createSelector(selectDynamicFamiliarsTricks, (dynamicFamiliarsTricks): GetById.Dynamic.FamiliarsTrick => id => dynamicFamiliarsTricks?.[id])
    export const FatePointSexSpecialAbility = createSelector(selectDynamicFatePointSexSpecialAbilities, (dynamicFatePointSexSpecialAbilities): GetById.Dynamic.FatePointSexSpecialAbility => id => dynamicFatePointSexSpecialAbilities?.[id])
    export const FatePointSpecialAbility = createSelector(selectDynamicFatePointSpecialAbilities, (dynamicFatePointSpecialAbilities): GetById.Dynamic.FatePointSpecialAbility => id => dynamicFatePointSpecialAbilities?.[id])
    export const FocusRule = createSelector(selectDynamicFocusRules, (dynamicFocusRules): GetById.Dynamic.FocusRule => id => dynamicFocusRules?.[id])
    export const FoolsHatEnchantment = createSelector(selectDynamicFoolsHatEnchantments, (dynamicFoolsHatEnchantments): GetById.Dynamic.FoolsHatEnchantment => id => dynamicFoolsHatEnchantments?.[id])
    // export const GemOrPreciousStone = createSelector(selectDynamicGemsAndPreciousStones, (dynamicGemsAndPreciousStones): GetById.Dynamic.GemOrPreciousStone => id => dynamicGemsAndPreciousStones?.[id])
    export const GeneralSpecialAbility = createSelector(selectDynamicGeneralSpecialAbilities, (dynamicGeneralSpecialAbilities): GetById.Dynamic.GeneralSpecialAbility => id => dynamicGeneralSpecialAbilities?.[id])
    export const GeodeRitual = createSelector(selectDynamicGeodeRituals, (dynamicGeodeRituals): GetById.Dynamic.GeodeRitual => id => dynamicGeodeRituals?.[id])
    // export const IlluminationLightSource = createSelector(selectDynamicIlluminationLightSources, (dynamicIlluminationLightSources): GetById.Dynamic.IlluminationLightSource => id => dynamicIlluminationLightSources?.[id])
    // export const IlluminationRefillsOrSupplies = createSelector(selectDynamicIlluminationRefillsAndSupplies, (dynamicIlluminationRefillsAndSupplies): GetById.Dynamic.IlluminationRefillsOrSupplies => id => dynamicIlluminationRefillsAndSupplies?.[id])
    export const InstrumentEnchantment = createSelector(selectDynamicInstrumentEnchantments, (dynamicInstrumentEnchantments): GetById.Dynamic.InstrumentEnchantment => id => dynamicInstrumentEnchantments?.[id])
    export const JesterTrick = createSelector(selectDynamicJesterTricks, (dynamicJesterTricks): GetById.Dynamic.JesterTrick => id => dynamicJesterTricks?.[id])
    // export const Jewelry = createSelector(selectDynamicJewelry, (dynamicJewelry): GetById.Dynamic.Jewelry => id => dynamicJewelry?.[id])
    export const KarmaSpecialAbility = createSelector(selectDynamicKarmaSpecialAbilities, (dynamicKarmaSpecialAbilities): GetById.Dynamic.KarmaSpecialAbility => id => dynamicKarmaSpecialAbilities?.[id])
    export const Krallenkettenzauber = createSelector(selectDynamicKrallenkettenzauber, (dynamicKrallenkettenzauber): GetById.Dynamic.Krallenkettenzauber => id => dynamicKrallenkettenzauber?.[id])
    // export const Liebesspielzeug = createSelector(selectDynamicLiebesspielzeug, (dynamicLiebesspielzeug): GetById.Dynamic.Liebesspielzeug => id => dynamicLiebesspielzeug?.[id])
    export const LiturgicalChant = createSelector(selectDynamicLiturgicalChants, (dynamicLiturgicalChants): GetById.Dynamic.LiturgicalChant => id => dynamicLiturgicalChants?.[id])
    export const LiturgicalStyleSpecialAbility = createSelector(selectDynamicLiturgicalStyleSpecialAbilities, (dynamicLiturgicalStyleSpecialAbilities): GetById.Dynamic.LiturgicalStyleSpecialAbility => id => dynamicLiturgicalStyleSpecialAbilities?.[id])
    // export const LuxuryGood = createSelector(selectDynamicLuxuryGoods, (dynamicLuxuryGoods): GetById.Dynamic.LuxuryGood => id => dynamicLuxuryGoods?.[id])
    export const LycantropicGift = createSelector(selectDynamicLycantropicGifts, (dynamicLycantropicGifts): GetById.Dynamic.LycantropicGift => id => dynamicLycantropicGifts?.[id])
    // export const MagicalArtifact = createSelector(selectDynamicMagicalArtifacts, (dynamicMagicalArtifacts): GetById.Dynamic.MagicalArtifact => id => dynamicMagicalArtifacts?.[id])
    export const MagicalDance = createSelector(selectDynamicMagicalDances, (dynamicMagicalDances): GetById.Dynamic.MagicalDance => id => dynamicMagicalDances?.[id])
    export const MagicalMelody = createSelector(selectDynamicMagicalMelodies, (dynamicMagicalMelodies): GetById.Dynamic.MagicalMelody => id => dynamicMagicalMelodies?.[id])
    export const MagicalRune = createSelector(selectDynamicMagicalRunes, (dynamicMagicalRunes): GetById.Dynamic.MagicalRune => id => dynamicMagicalRunes?.[id])
    export const MagicalSign = createSelector(selectDynamicMagicalSigns, (dynamicMagicalSigns): GetById.Dynamic.MagicalSign => id => dynamicMagicalSigns?.[id])
    export const MagicalSpecialAbility = createSelector(selectDynamicMagicalSpecialAbilities, (dynamicMagicalSpecialAbilities): GetById.Dynamic.MagicalSpecialAbility => id => dynamicMagicalSpecialAbilities?.[id])
    export const MagicalTradition = createSelector(selectDynamicMagicalTraditions, (dynamicMagicalTraditions): GetById.Dynamic.MagicalTradition => id => dynamicMagicalTraditions?.[id])
    export const MagicStyleSpecialAbility = createSelector(selectDynamicMagicStyleSpecialAbilities, (dynamicMagicStyleSpecialAbilities): GetById.Dynamic.MagicStyleSpecialAbility => id => dynamicMagicStyleSpecialAbilities?.[id])
    // export const MetaCondition = createSelector(selectDynamicMetaConditions, (dynamicMetaConditions): GetById.Dynamic.MetaCondition => id => dynamicMetaConditions?.[id])
    // export const MusicalInstrument = createSelector(selectDynamicMusicalInstruments, (dynamicMusicalInstruments): GetById.Dynamic.MusicalInstrument => id => dynamicMusicalInstruments?.[id])
    export const OptionalRule = createSelector(selectDynamicOptionalRules, (dynamicOptionalRules): GetById.Dynamic.OptionalRule => id => dynamicOptionalRules?.[id])
    export const OrbEnchantment = createSelector(selectDynamicOrbEnchantments, (dynamicOrbEnchantments): GetById.Dynamic.OrbEnchantment => id => dynamicOrbEnchantments?.[id])
    // export const OrienteeringAid = createSelector(selectDynamicOrienteeringAids, (dynamicOrienteeringAids): GetById.Dynamic.OrienteeringAid => id => dynamicOrienteeringAids?.[id])
    export const PactGift = createSelector(selectDynamicPactGifts, (dynamicPactGifts): GetById.Dynamic.PactGift => id => dynamicPactGifts?.[id])
    // export const PersonalityTrait = createSelector(selectDynamicPersonalityTraits, (dynamicPersonalityTraits): GetById.Dynamic.PersonalityTrait => id => dynamicPersonalityTraits?.[id])
    // export const Poison = createSelector(selectDynamicPoisons, (dynamicPoisons): GetById.Dynamic.Poison => id => dynamicPoisons?.[id])
    export const ProtectiveWardingCircleSpecialAbility = createSelector(selectDynamicProtectiveWardingCircleSpecialAbilities, (dynamicProtectiveWardingCircleSpecialAbilities): GetById.Dynamic.ProtectiveWardingCircleSpecialAbility => id => dynamicProtectiveWardingCircleSpecialAbilities?.[id])
    // export const Publication = createSelector(selectDynamicPublications, (dynamicPublications): GetById.Dynamic.Publication => id => dynamicPublications?.[id])
    export const RangedCombatTechnique = createSelector(selectDynamicRangedCombatTechniques, (dynamicRangedCombatTechniques): GetById.Dynamic.RangedCombatTechnique => id => dynamicRangedCombatTechniques?.[id])
    export const RingEnchantment = createSelector(selectDynamicRingEnchantments, (dynamicRingEnchantments): GetById.Dynamic.RingEnchantment => id => dynamicRingEnchantments?.[id])
    export const Ritual = createSelector(selectDynamicRituals, (dynamicRituals): GetById.Dynamic.Ritual => id => dynamicRituals?.[id])
    // export const RopeOrChain = createSelector(selectDynamicRopesAndChains, (dynamicRopesAndChains): GetById.Dynamic.RopeOrChain => id => dynamicRopesAndChains?.[id])
    export const Sermon = createSelector(selectDynamicSermons, (dynamicSermons): GetById.Dynamic.Sermon => id => dynamicSermons?.[id])
    export const SexSpecialAbility = createSelector(selectDynamicSexSpecialAbilities, (dynamicSexSpecialAbilities): GetById.Dynamic.SexSpecialAbility => id => dynamicSexSpecialAbilities?.[id])
    export const SickleRitual = createSelector(selectDynamicSickleRituals, (dynamicSickleRituals): GetById.Dynamic.SickleRitual => id => dynamicSickleRituals?.[id])
    export const SikaryanDrainSpecialAbility = createSelector(selectDynamicSikaryanDrainSpecialAbilities, (dynamicSikaryanDrainSpecialAbilities): GetById.Dynamic.SikaryanDrainSpecialAbility => id => dynamicSikaryanDrainSpecialAbilities?.[id])
    export const Skill = createSelector(selectDynamicSkills, (dynamicSkills): GetById.Dynamic.Skill => id => dynamicSkills?.[id])
    export const SkillStyleSpecialAbility = createSelector(selectDynamicSkillStyleSpecialAbilities, (dynamicSkillStyleSpecialAbilities): GetById.Dynamic.SkillStyleSpecialAbility => id => dynamicSkillStyleSpecialAbilities?.[id])
    export const Spell = createSelector(selectDynamicSpells, (dynamicSpells): GetById.Dynamic.Spell => id => dynamicSpells?.[id])
    export const SpellSwordEnchantment = createSelector(selectDynamicSpellSwordEnchantments, (dynamicSpellSwordEnchantments): GetById.Dynamic.SpellSwordEnchantment => id => dynamicSpellSwordEnchantments?.[id])
    export const StaffEnchantment = createSelector(selectDynamicStaffEnchantments, (dynamicStaffEnchantments): GetById.Dynamic.StaffEnchantment => id => dynamicStaffEnchantments?.[id])
    export const State = createSelector(selectDynamicStates, (dynamicStates): GetById.Dynamic.State => id => dynamicStates?.[id])
    // export const Stationary = createSelector(selectDynamicStationary, (dynamicStationary): GetById.Dynamic.Stationary => id => dynamicStationary?.[id])
    // export const Talisman = createSelector(selectDynamicTalismans, (dynamicTalismans): GetById.Dynamic.Talisman => id => dynamicTalismans?.[id])
    // export const ThievesTool = createSelector(selectDynamicThievesTools, (dynamicThievesTools): GetById.Dynamic.ThievesTool => id => dynamicThievesTools?.[id])
    // export const ToolOfTheTrade = createSelector(selectDynamicToolsOfTheTrade, (dynamicToolsOfTheTrade): GetById.Dynamic.ToolOfTheTrade => id => dynamicToolsOfTheTrade?.[id])
    export const ToyEnchantment = createSelector(selectDynamicToyEnchantments, (dynamicToyEnchantments): GetById.Dynamic.ToyEnchantment => id => dynamicToyEnchantments?.[id])
    // export const TravelGearOrTool = createSelector(selectDynamicTravelGearAndTools, (dynamicTravelGearAndTools): GetById.Dynamic.TravelGearOrTool => id => dynamicTravelGearAndTools?.[id])
    export const Trinkhornzauber = createSelector(selectDynamicTrinkhornzauber, (dynamicTrinkhornzauber): GetById.Dynamic.Trinkhornzauber => id => dynamicTrinkhornzauber?.[id])
    export const VampiricGift = createSelector(selectDynamicVampiricGifts, (dynamicVampiricGifts): GetById.Dynamic.VampiricGift => id => dynamicVampiricGifts?.[id])
    // export const Vehicle = createSelector(selectDynamicVehicles, (dynamicVehicles): GetById.Dynamic.Vehicle => id => dynamicVehicles?.[id])
    export const Vision = createSelector(selectDynamicVisions, (dynamicVisions): GetById.Dynamic.Vision => id => dynamicVisions?.[id])
    export const WandEnchantment = createSelector(selectDynamicWandEnchantments, (dynamicWandEnchantments): GetById.Dynamic.WandEnchantment => id => dynamicWandEnchantments?.[id])
    // export const WeaponAccessory = createSelector(selectDynamicWeaponAccessories, (dynamicWeaponAccessories): GetById.Dynamic.WeaponAccessory => id => dynamicWeaponAccessories?.[id])
    export const WeaponEnchantment = createSelector(selectDynamicWeaponEnchantments, (dynamicWeaponEnchantments): GetById.Dynamic.WeaponEnchantment => id => dynamicWeaponEnchantments?.[id])
    // export const Weapon = createSelector(selectDynamicWeapons, (dynamicWeapons): GetById.Dynamic.Weapon => id => dynamicWeapons?.[id])
    export const ZibiljaRitual = createSelector(selectDynamicZibiljaRituals, (dynamicZibiljaRituals): GetById.Dynamic.ZibiljaRitual => id => dynamicZibiljaRituals?.[id])
  }
}

// prettier-ignore
export namespace SelectAll {
  export namespace Static {
    export const AdvancedCombatSpecialAbilities = createSelector(selectDatabase, (database): All.Static.AdvancedCombatSpecialAbilities => Object.values(database.advancedCombatSpecialAbilities))
    export const AdvancedKarmaSpecialAbilities = createSelector(selectDatabase, (database): All.Static.AdvancedKarmaSpecialAbilities => Object.values(database.advancedKarmaSpecialAbilities))
    export const AdvancedMagicalSpecialAbilities = createSelector(selectDatabase, (database): All.Static.AdvancedMagicalSpecialAbilities => Object.values(database.advancedMagicalSpecialAbilities))
    export const AdvancedSkillSpecialAbilities = createSelector(selectDatabase, (database): All.Static.AdvancedSkillSpecialAbilities => Object.values(database.advancedSkillSpecialAbilities))
    export const Advantages = createSelector(selectDatabase, (database): All.Static.Advantages => Object.values(database.advantages))
    export const Ammunition = createSelector(selectDatabase, (database): All.Static.Ammunition => Object.values(database.ammunition))
    export const AncestorGlyphs = createSelector(selectDatabase, (database): All.Static.AncestorGlyphs => Object.values(database.ancestorGlyphs))
    export const AnimalCare = createSelector(selectDatabase, (database): All.Static.AnimalCare => Object.values(database.animalCare))
    export const AnimalDiseases = createSelector(selectDatabase, (database): All.Static.AnimalDiseases => Object.values(database.animalDiseases))
    export const Animals = createSelector(selectDatabase, (database): All.Static.Animals => Object.values(database.animals))
    export const AnimalShapePaths = createSelector(selectDatabase, (database): All.Static.AnimalShapePaths => Object.values(database.animalShapePaths))
    export const AnimalShapes = createSelector(selectDatabase, (database): All.Static.AnimalShapes => Object.values(database.animalShapes))
    export const AnimalShapeSizes = createSelector(selectDatabase, (database): All.Static.AnimalShapeSizes => Object.values(database.animalShapeSizes))
    export const AnimalTypes = createSelector(selectDatabase, (database): All.Static.AnimalTypes => Object.values(database.animalTypes))
    export const AnimistPowers = createSelector(selectDatabase, (database): All.Static.AnimistPowers => Object.values(database.animistPowers))
    export const AnimistPowerTribes = createSelector(selectDatabase, (database): All.Static.AnimistPowerTribes => Object.values(database.animistPowerTribes))
    export const ArcaneBardTraditions = createSelector(selectDatabase, (database): All.Static.ArcaneBardTraditions => Object.values(database.arcaneBardTraditions))
    export const ArcaneDancerTraditions = createSelector(selectDatabase, (database): All.Static.ArcaneDancerTraditions => Object.values(database.arcaneDancerTraditions))
    export const ArcaneOrbEnchantments = createSelector(selectDatabase, (database): All.Static.ArcaneOrbEnchantments => Object.values(database.arcaneOrbEnchantments))
    export const Armors = createSelector(selectDatabase, (database): All.Static.Armors => Object.values(database.armors))
    export const ArmorTypes = createSelector(selectDatabase, (database): All.Static.ArmorTypes => Object.values(database.armorTypes))
    export const Aspects = createSelector(selectDatabase, (database): All.Static.Aspects => Object.values(database.aspects))
    export const AttireEnchantments = createSelector(selectDatabase, (database): All.Static.AttireEnchantments => Object.values(database.attireEnchantments))
    export const Attributes = createSelector(selectDatabase, (database): All.Static.Attributes => Object.values(database.attributes))
    export const BandagesAndRemedies = createSelector(selectDatabase, (database): All.Static.BandagesAndRemedies => Object.values(database.bandagesAndRemedies))
    export const BlessedTraditions = createSelector(selectDatabase, (database): All.Static.BlessedTraditions => Object.values(database.blessedTraditions))
    export const Blessings = createSelector(selectDatabase, (database): All.Static.Blessings => Object.values(database.blessings))
    export const Books = createSelector(selectDatabase, (database): All.Static.Books => Object.values(database.books))
    export const BowlEnchantments = createSelector(selectDatabase, (database): All.Static.BowlEnchantments => Object.values(database.bowlEnchantments))
    export const BrawlingSpecialAbilities = createSelector(selectDatabase, (database): All.Static.BrawlingSpecialAbilities => Object.values(database.brawlingSpecialAbilities))
    export const Brews = createSelector(selectDatabase, (database): All.Static.Brews => Object.values(database.brews))
    export const Cantrips = createSelector(selectDatabase, (database): All.Static.Cantrips => Object.values(database.cantrips))
    export const CauldronEnchantments = createSelector(selectDatabase, (database): All.Static.CauldronEnchantments => Object.values(database.cauldronEnchantments))
    export const CeremonialItems = createSelector(selectDatabase, (database): All.Static.CeremonialItems => Object.values(database.ceremonialItems))
    export const CeremonialItemSpecialAbilities = createSelector(selectDatabase, (database): All.Static.CeremonialItemSpecialAbilities => Object.values(database.ceremonialItemSpecialAbilities))
    export const Ceremonies = createSelector(selectDatabase, (database): All.Static.Ceremonies => Object.values(database.ceremonies))
    export const ChronicleEnchantments = createSelector(selectDatabase, (database): All.Static.ChronicleEnchantments => Object.values(database.chronicleEnchantments))
    export const CloseCombatTechniques = createSelector(selectDatabase, (database): All.Static.CloseCombatTechniques => Object.values(database.closeCombatTechniques))
    export const Clothes = createSelector(selectDatabase, (database): All.Static.Clothes => Object.values(database.clothes))
    export const CombatSpecialAbilities = createSelector(selectDatabase, (database): All.Static.CombatSpecialAbilities => Object.values(database.combatSpecialAbilities))
    export const CombatStyleSpecialAbilities = createSelector(selectDatabase, (database): All.Static.CombatStyleSpecialAbilities => Object.values(database.combatStyleSpecialAbilities))
    export const CommandSpecialAbilities = createSelector(selectDatabase, (database): All.Static.CommandSpecialAbilities => Object.values(database.commandSpecialAbilities))
    export const Conditions = createSelector(selectDatabase, (database): All.Static.Conditions => Object.values(database.conditions))
    export const Containers = createSelector(selectDatabase, (database): All.Static.Containers => Object.values(database.containers))
    export const Continents = createSelector(selectDatabase, (database): All.Static.Continents => Object.values(database.continents))
    export const CoreRules = createSelector(selectDatabase, (database): All.Static.CoreRules => Object.values(database.coreRules))
    export const Cultures = createSelector(selectDatabase, (database): All.Static.Cultures => Object.values(database.cultures))
    export const Curses = createSelector(selectDatabase, (database): All.Static.Curses => Object.values(database.curses))
    export const DaggerRituals = createSelector(selectDatabase, (database): All.Static.DaggerRituals => Object.values(database.daggerRituals))
    export const DerivedCharacteristics = createSelector(selectDatabase, (database): All.Static.DerivedCharacteristics => Object.values(database.derivedCharacteristics))
    export const Disadvantages = createSelector(selectDatabase, (database): All.Static.Disadvantages => Object.values(database.disadvantages))
    export const Diseases = createSelector(selectDatabase, (database): All.Static.Diseases => Object.values(database.diseases))
    export const DominationRituals = createSelector(selectDatabase, (database): All.Static.DominationRituals => Object.values(database.dominationRituals))
    export const Elements = createSelector(selectDatabase, (database): All.Static.Elements => Object.values(database.elements))
    export const Elixirs = createSelector(selectDatabase, (database): All.Static.Elixirs => Object.values(database.elixirs))
    export const ElvenMagicalSongs = createSelector(selectDatabase, (database): All.Static.ElvenMagicalSongs => Object.values(database.elvenMagicalSongs))
    export const EquipmentOfBlessedOnes = createSelector(selectDatabase, (database): All.Static.EquipmentOfBlessedOnes => Object.values(database.equipmentOfBlessedOnes))
    export const EquipmentPackages = createSelector(selectDatabase, (database): All.Static.EquipmentPackages => Object.values(database.equipmentPackages))
    export const ExperienceLevels = createSelector(selectDatabase, (database): All.Static.ExperienceLevels => Object.values(database.experienceLevels))
    export const EyeColors = createSelector(selectDatabase, (database): All.Static.EyeColors => Object.values(database.eyeColors))
    export const FamiliarSpecialAbilities = createSelector(selectDatabase, (database): All.Static.FamiliarSpecialAbilities => Object.values(database.familiarSpecialAbilities))
    export const FamiliarsTricks = createSelector(selectDatabase, (database): All.Static.FamiliarsTricks => Object.values(database.familiarsTricks))
    export const FatePointSexSpecialAbilities = createSelector(selectDatabase, (database): All.Static.FatePointSexSpecialAbilities => Object.values(database.fatePointSexSpecialAbilities))
    export const FatePointSpecialAbilities = createSelector(selectDatabase, (database): All.Static.FatePointSpecialAbilities => Object.values(database.fatePointSpecialAbilities))
    export const FocusRules = createSelector(selectDatabase, (database): All.Static.FocusRules => Object.values(database.focusRules))
    export const FocusRuleSubjects = createSelector(selectDatabase, (database): All.Static.FocusRuleSubjects => Object.values(database.focusRuleSubjects))
    export const FoolsHatEnchantments = createSelector(selectDatabase, (database): All.Static.FoolsHatEnchantments => Object.values(database.foolsHatEnchantments))
    export const GemsAndPreciousStones = createSelector(selectDatabase, (database): All.Static.GemsAndPreciousStones => Object.values(database.gemsAndPreciousStones))
    export const GeneralSpecialAbilities = createSelector(selectDatabase, (database): All.Static.GeneralSpecialAbilities => Object.values(database.generalSpecialAbilities))
    export const GeodeRituals = createSelector(selectDatabase, (database): All.Static.GeodeRituals => Object.values(database.geodeRituals))
    export const HairColors = createSelector(selectDatabase, (database): All.Static.HairColors => Object.values(database.hairColors))
    export const IlluminationLightSources = createSelector(selectDatabase, (database): All.Static.IlluminationLightSources => Object.values(database.illuminationLightSources))
    export const IlluminationRefillsAndSupplies = createSelector(selectDatabase, (database): All.Static.IlluminationRefillsAndSupplies => Object.values(database.illuminationRefillsAndSupplies))
    export const InstrumentEnchantments = createSelector(selectDatabase, (database): All.Static.InstrumentEnchantments => Object.values(database.instrumentEnchantments))
    export const JesterTricks = createSelector(selectDatabase, (database): All.Static.JesterTricks => Object.values(database.jesterTricks))
    export const Jewelry = createSelector(selectDatabase, (database): All.Static.Jewelry => Object.values(database.jewelry))
    export const KarmaSpecialAbilities = createSelector(selectDatabase, (database): All.Static.KarmaSpecialAbilities => Object.values(database.karmaSpecialAbilities))
    export const Kirchenpraegungen = createSelector(selectDatabase, (database): All.Static.Kirchenpraegungen => Object.values(database.kirchenpraegungen))
    export const Krallenkettenzauber = createSelector(selectDatabase, (database): All.Static.Krallenkettenzauber => Object.values(database.krallenkettenzauber))
    export const Languages = createSelector(selectDatabase, (database): All.Static.Languages => Object.values(database.languages))
    export const LessonsCurricula = createSelector(selectDatabase, (database): All.Static.LessonsCurricula => Object.values(database.lessonsCurricula))
    export const LessonsGuidelines = createSelector(selectDatabase, (database): All.Static.LessonsGuidelines => Object.values(database.lessonsGuidelines))
    export const Liebesspielzeug = createSelector(selectDatabase, (database): All.Static.Liebesspielzeug => Object.values(database.liebesspielzeug))
    export const LiturgicalChants = createSelector(selectDatabase, (database): All.Static.LiturgicalChants => Object.values(database.liturgicalChants))
    export const LiturgicalStyleSpecialAbilities = createSelector(selectDatabase, (database): All.Static.LiturgicalStyleSpecialAbilities => Object.values(database.liturgicalStyleSpecialAbilities))
    export const Locales = createSelector(selectDatabase, (database): All.Static.Locales => Object.values(database.locales))
    export const LuxuryGoods = createSelector(selectDatabase, (database): All.Static.LuxuryGoods => Object.values(database.luxuryGoods))
    export const LycantropicGifts = createSelector(selectDatabase, (database): All.Static.LycantropicGifts => Object.values(database.lycantropicGifts))
    export const MagicalArtifacts = createSelector(selectDatabase, (database): All.Static.MagicalArtifacts => Object.values(database.magicalArtifacts))
    export const MagicalDances = createSelector(selectDatabase, (database): All.Static.MagicalDances => Object.values(database.magicalDances))
    export const MagicalMelodies = createSelector(selectDatabase, (database): All.Static.MagicalMelodies => Object.values(database.magicalMelodies))
    export const MagicalRunes = createSelector(selectDatabase, (database): All.Static.MagicalRunes => Object.values(database.magicalRunes))
    export const MagicalSigns = createSelector(selectDatabase, (database): All.Static.MagicalSigns => Object.values(database.magicalSigns))
    export const MagicalSpecialAbilities = createSelector(selectDatabase, (database): All.Static.MagicalSpecialAbilities => Object.values(database.magicalSpecialAbilities))
    export const MagicalTraditions = createSelector(selectDatabase, (database): All.Static.MagicalTraditions => Object.values(database.magicalTraditions))
    export const MagicStyleSpecialAbilities = createSelector(selectDatabase, (database): All.Static.MagicStyleSpecialAbilities => Object.values(database.magicStyleSpecialAbilities))
    export const MetaConditions = createSelector(selectDatabase, (database): All.Static.MetaConditions => Object.values(database.metaConditions))
    export const MusicalInstruments = createSelector(selectDatabase, (database): All.Static.MusicalInstruments => Object.values(database.musicalInstruments))
    export const OptionalRules = createSelector(selectDatabase, (database): All.Static.OptionalRules => Object.values(database.optionalRules))
    export const OrbEnchantments = createSelector(selectDatabase, (database): All.Static.OrbEnchantments => Object.values(database.orbEnchantments))
    export const OrienteeringAids = createSelector(selectDatabase, (database): All.Static.OrienteeringAids => Object.values(database.orienteeringAids))
    export const PactCategories = createSelector(selectDatabase, (database): All.Static.PactCategories => Object.values(database.pactCategories))
    export const PactGifts = createSelector(selectDatabase, (database): All.Static.PactGifts => Object.values(database.pactGifts))
    export const PatronCategories = createSelector(selectDatabase, (database): All.Static.PatronCategories => Object.values(database.patronCategories))
    export const Patrons = createSelector(selectDatabase, (database): All.Static.Patrons => Object.values(database.patrons))
    export const PersonalityTraits = createSelector(selectDatabase, (database): All.Static.PersonalityTraits => Object.values(database.personalityTraits))
    export const Poisons = createSelector(selectDatabase, (database): All.Static.Poisons => Object.values(database.poisons))
    export const Professions = createSelector(selectDatabase, (database): All.Static.Professions => Object.values(database.professions))
    export const Properties = createSelector(selectDatabase, (database): All.Static.Properties => Object.values(database.properties))
    export const ProtectiveWardingCircleSpecialAbilities = createSelector(selectDatabase, (database): All.Static.ProtectiveWardingCircleSpecialAbilities => Object.values(database.protectiveWardingCircleSpecialAbilities))
    export const Publications = createSelector(selectDatabase, (database): All.Static.Publications => Object.values(database.publications))
    export const Races = createSelector(selectDatabase, (database): All.Static.Races => Object.values(database.races))
    export const RangedCombatTechniques = createSelector(selectDatabase, (database): All.Static.RangedCombatTechniques => Object.values(database.rangedCombatTechniques))
    export const Reaches = createSelector(selectDatabase, (database): All.Static.Reaches => Object.values(database.reaches))
    export const Regions = createSelector(selectDatabase, (database): All.Static.Regions => Object.values(database.regions))
    export const RingEnchantments = createSelector(selectDatabase, (database): All.Static.RingEnchantments => Object.values(database.ringEnchantments))
    export const Rituals = createSelector(selectDatabase, (database): All.Static.Rituals => Object.values(database.rituals))
    export const RopesAndChains = createSelector(selectDatabase, (database): All.Static.RopesAndChains => Object.values(database.ropesAndChains))
    export const Scripts = createSelector(selectDatabase, (database): All.Static.Scripts => Object.values(database.scripts))
    export const Sermons = createSelector(selectDatabase, (database): All.Static.Sermons => Object.values(database.sermons))
    export const Services = createSelector(selectDatabase, (database): All.Static.Services => Object.values(database.services))
    export const SexPractices = createSelector(selectDatabase, (database): All.Static.SexPractices => Object.values(database.sexPractices))
    export const SexSpecialAbilities = createSelector(selectDatabase, (database): All.Static.SexSpecialAbilities => Object.values(database.sexSpecialAbilities))
    export const SickleRituals = createSelector(selectDatabase, (database): All.Static.SickleRituals => Object.values(database.sickleRituals))
    export const SikaryanDrainSpecialAbilities = createSelector(selectDatabase, (database): All.Static.SikaryanDrainSpecialAbilities => Object.values(database.sikaryanDrainSpecialAbilities))
    export const SkillGroups = createSelector(selectDatabase, (database): All.Static.SkillGroups => Object.values(database.skillGroups))
    export const SkillModificationLevels = createSelector(selectDatabase, (database): All.Static.SkillModificationLevels => Object.values(database.skillModificationLevels))
    export const Skills = createSelector(selectDatabase, (database): All.Static.Skills => Object.values(database.skills))
    export const SkillStyleSpecialAbilities = createSelector(selectDatabase, (database): All.Static.SkillStyleSpecialAbilities => Object.values(database.skillStyleSpecialAbilities))
    export const SocialStatuses = createSelector(selectDatabase, (database): All.Static.SocialStatuses => Object.values(database.socialStatuses))
    export const Spells = createSelector(selectDatabase, (database): All.Static.Spells => Object.values(database.spells))
    export const SpellSwordEnchantments = createSelector(selectDatabase, (database): All.Static.SpellSwordEnchantments => Object.values(database.spellSwordEnchantments))
    export const StaffEnchantments = createSelector(selectDatabase, (database): All.Static.StaffEnchantments => Object.values(database.staffEnchantments))
    export const States = createSelector(selectDatabase, (database): All.Static.States => Object.values(database.states))
    export const Stationary = createSelector(selectDatabase, (database): All.Static.Stationary => Object.values(database.stationary))
    export const Talismans = createSelector(selectDatabase, (database): All.Static.Talismans => Object.values(database.talismans))
    export const TargetCategories = createSelector(selectDatabase, (database): All.Static.TargetCategories => Object.values(database.targetCategories))
    export const ThievesTools = createSelector(selectDatabase, (database): All.Static.ThievesTools => Object.values(database.thievesTools))
    export const ToolsOfTheTrade = createSelector(selectDatabase, (database): All.Static.ToolsOfTheTrade => Object.values(database.toolsOfTheTrade))
    export const ToyEnchantments = createSelector(selectDatabase, (database): All.Static.ToyEnchantments => Object.values(database.toyEnchantments))
    export const TradeSecrets = createSelector(selectDatabase, (database): All.Static.TradeSecrets => Object.values(database.tradeSecrets))
    export const TravelGearAndTools = createSelector(selectDatabase, (database): All.Static.TravelGearAndTools => Object.values(database.travelGearAndTools))
    export const Trinkhornzauber = createSelector(selectDatabase, (database): All.Static.Trinkhornzauber => Object.values(database.trinkhornzauber))
    export const UI = createSelector(selectDatabase, (database): All.Static.UI => Object.values(database.ui))
    export const VampiricGifts = createSelector(selectDatabase, (database): All.Static.VampiricGifts => Object.values(database.vampiricGifts))
    export const Vehicles = createSelector(selectDatabase, (database): All.Static.Vehicles => Object.values(database.vehicles))
    export const Visions = createSelector(selectDatabase, (database): All.Static.Visions => Object.values(database.visions))
    export const WandEnchantments = createSelector(selectDatabase, (database): All.Static.WandEnchantments => Object.values(database.wandEnchantments))
    export const WeaponAccessories = createSelector(selectDatabase, (database): All.Static.WeaponAccessories => Object.values(database.weaponAccessories))
    export const WeaponEnchantments = createSelector(selectDatabase, (database): All.Static.WeaponEnchantments => Object.values(database.weaponEnchantments))
    export const Weapons = createSelector(selectDatabase, (database): All.Static.Weapons => Object.values(database.weapons))
    export const ZibiljaRituals = createSelector(selectDatabase, (database): All.Static.ZibiljaRituals => Object.values(database.zibiljaRituals))
  }

  export namespace Dynamic {
    export const AdvancedCombatSpecialAbilities = createSelector(selectDynamicAdvancedCombatSpecialAbilities, (advancedCombatSpecialAbilities): All.Dynamic.AdvancedCombatSpecialAbilities => Object.values(advancedCombatSpecialAbilities ?? {}))
    export const AdvancedKarmaSpecialAbilities = createSelector(selectDynamicAdvancedKarmaSpecialAbilities, (advancedKarmaSpecialAbilities): All.Dynamic.AdvancedKarmaSpecialAbilities => Object.values(advancedKarmaSpecialAbilities ?? {}))
    export const AdvancedMagicalSpecialAbilities = createSelector(selectDynamicAdvancedMagicalSpecialAbilities, (advancedMagicalSpecialAbilities): All.Dynamic.AdvancedMagicalSpecialAbilities => Object.values(advancedMagicalSpecialAbilities ?? {}))
    export const AdvancedSkillSpecialAbilities = createSelector(selectDynamicAdvancedSkillSpecialAbilities, (advancedSkillSpecialAbilities): All.Dynamic.AdvancedSkillSpecialAbilities => Object.values(advancedSkillSpecialAbilities ?? {}))
    export const Advantages = createSelector(selectDynamicAdvantages, (advantages): All.Dynamic.Advantages => Object.values(advantages ?? {}))
    // export const Ammunition = createSelector(selectDynamicAmmunition, (ammunition): GetAll.Dynamic.Ammunition => Object.values(ammunition ?? {}))
    export const AncestorGlyphs = createSelector(selectDynamicAncestorGlyphs, (ancestorGlyphs): All.Dynamic.AncestorGlyphs => Object.values(ancestorGlyphs ?? {}))
    // export const AnimalCare = createSelector(selectDynamicAnimalCare, (animalCare): GetAll.Dynamic.AnimalCare => Object.values(animalCare ?? {}))
    export const AnimistPowers = createSelector(selectDynamicAnimistPowers, (animistPowers): All.Dynamic.AnimistPowers => Object.values(animistPowers ?? {}))
    export const ArcaneOrbEnchantments = createSelector(selectDynamicArcaneOrbEnchantments, (arcaneOrbEnchantments): All.Dynamic.ArcaneOrbEnchantments => Object.values(arcaneOrbEnchantments ?? {}))
    // export const Armor = createSelector(selectDynamicArmor, (armor): GetAll.Dynamic.Armor => Object.values(armor ?? {}))
    export const AttireEnchantments = createSelector(selectDynamicAttireEnchantments, (attireEnchantments): All.Dynamic.AttireEnchantments => Object.values(attireEnchantments ?? {}))
    export const Attributes = createSelector(selectDynamicAttributes, (attributes): All.Dynamic.Attributes => Object.values(attributes ?? {}))
    // export const BandagesAndRemedies = createSelector(selectDynamicBandagesAndRemedies, (bandagesAndRemedies): GetAll.Dynamic.BandagesAndRemedies => Object.values(bandagesAndRemedies ?? {}))
    export const BlessedTraditions = createSelector(selectDynamicBlessedTraditions, (blessedTraditions): All.Dynamic.BlessedTraditions => Object.values(blessedTraditions ?? {}))
    export const Blessings = createSelector(selectDynamicBlessings, (blessings): All.Dynamic.Blessings => Object.values(blessings ?? {}))
    // export const Books = createSelector(selectDynamicBooks, (books): GetAll.Dynamic.Books => Object.values(books ?? {}))
    export const BowlEnchantments = createSelector(selectDynamicBowlEnchantments, (bowlEnchantments): All.Dynamic.BowlEnchantments => Object.values(bowlEnchantments ?? {}))
    export const BrawlingSpecialAbilities = createSelector(selectDynamicBrawlingSpecialAbilities, (brawlingSpecialAbilities): All.Dynamic.BrawlingSpecialAbilities => Object.values(brawlingSpecialAbilities ?? {}))
    export const Cantrips = createSelector(selectDynamicCantrips, (cantrips): All.Dynamic.Cantrips => Object.values(cantrips ?? {}))
    export const CauldronEnchantments = createSelector(selectDynamicCauldronEnchantments, (cauldronEnchantments): All.Dynamic.CauldronEnchantments => Object.values(cauldronEnchantments ?? {}))
    // export const CeremonialItems = createSelector(selectDynamicCeremonialItems, (ceremonialItems): GetAll.Dynamic.CeremonialItems => Object.values(ceremonialItems ?? {}))
    export const CeremonialItemSpecialAbilities = createSelector(selectDynamicCeremonialItemSpecialAbilities, (ceremonialItemSpecialAbilities): All.Dynamic.CeremonialItemSpecialAbilities => Object.values(ceremonialItemSpecialAbilities ?? {}))
    export const Ceremonies = createSelector(selectDynamicCeremonies, (ceremonies): All.Dynamic.Ceremonies => Object.values(ceremonies ?? {}))
    export const ChronicleEnchantments = createSelector(selectDynamicChronicleEnchantments, (chronicleEnchantments): All.Dynamic.ChronicleEnchantments => Object.values(chronicleEnchantments ?? {}))
    export const CloseCombatTechniques = createSelector(selectDynamicCloseCombatTechniques, (closeCombatTechniques): All.Dynamic.CloseCombatTechniques => Object.values(closeCombatTechniques ?? {}))
    // export const Clothes = createSelector(selectDynamicClothes, (clothes): GetAll.Dynamic.Clothes => Object.values(clothes ?? {}))
    export const CombatSpecialAbilities = createSelector(selectDynamicCombatSpecialAbilities, (combatSpecialAbilities): All.Dynamic.CombatSpecialAbilities => Object.values(combatSpecialAbilities ?? {}))
    export const CombatStyleSpecialAbilities = createSelector(selectDynamicCombatStyleSpecialAbilities, (combatStyleSpecialAbilities): All.Dynamic.CombatStyleSpecialAbilities => Object.values(combatStyleSpecialAbilities ?? {}))
    export const CommandSpecialAbilities = createSelector(selectDynamicCommandSpecialAbilities, (commandSpecialAbilities): All.Dynamic.CommandSpecialAbilities => Object.values(commandSpecialAbilities ?? {}))
    // export const Conditions = createSelector(selectDynamicConditions, (conditions): GetAll.Dynamic.Conditions => Object.values(conditions ?? {}))
    // export const Containers = createSelector(selectDynamicContainers, (containers): GetAll.Dynamic.Containers => Object.values(containers ?? {}))
    export const Curses = createSelector(selectDynamicCurses, (curses): All.Dynamic.Curses => Object.values(curses ?? {}))
    export const DaggerRituals = createSelector(selectDynamicDaggerRituals, (daggerRituals): All.Dynamic.DaggerRituals => Object.values(daggerRituals ?? {}))
    // export const DerivedCharacteristics = createSelector(selectDynamicDerivedCharacteristics, (derivedCharacteristics): GetAll.Dynamic.DerivedCharacteristics => Object.values(derivedCharacteristics ?? {}))
    export const Disadvantages = createSelector(selectDynamicDisadvantages, (disadvantages): All.Dynamic.Disadvantages => Object.values(disadvantages ?? {}))
    // export const Diseases = createSelector(selectDynamicDiseases, (diseases): GetAll.Dynamic.Diseases => Object.values(diseases ?? {}))
    export const DominationRituals = createSelector(selectDynamicDominationRituals, (dominationRituals): All.Dynamic.DominationRituals => Object.values(dominationRituals ?? {}))
    // export const Elixirs = createSelector(selectDynamicElixirs, (elixirs): GetAll.Dynamic.Elixirs => Object.values(elixirs ?? {}))
    export const ElvenMagicalSongs = createSelector(selectDynamicElvenMagicalSongs, (elvenMagicalSongs): All.Dynamic.ElvenMagicalSongs => Object.values(elvenMagicalSongs ?? {}))
    // export const EquipmentOfBlessedOnes = createSelector(selectDynamicEquipmentOfBlessedOnes, (equipmentOfBlessedOnes): GetAll.Dynamic.EquipmentOfBlessedOnes => Object.values(equipmentOfBlessedOnes ?? {}))
    export const FamiliarSpecialAbilities = createSelector(selectDynamicFamiliarSpecialAbilities, (familiarSpecialAbilities): All.Dynamic.FamiliarSpecialAbilities => Object.values(familiarSpecialAbilities ?? {}))
    // export const FamiliarsTricks = createSelector(selectDynamicFamiliarsTricks, (familiarsTricks): GetAll.Dynamic.FamiliarsTricks => Object.values(familiarsTricks ?? {}))
    export const FatePointSexSpecialAbilities = createSelector(selectDynamicFatePointSexSpecialAbilities, (fatePointSexSpecialAbilities): All.Dynamic.FatePointSexSpecialAbilities => Object.values(fatePointSexSpecialAbilities ?? {}))
    export const FatePointSpecialAbilities = createSelector(selectDynamicFatePointSpecialAbilities, (fatePointSpecialAbilities): All.Dynamic.FatePointSpecialAbilities => Object.values(fatePointSpecialAbilities ?? {}))
    export const FocusRules = createSelector(selectDynamicFocusRules, (focusRules): All.Dynamic.FocusRules => Object.values(focusRules ?? {}))
    export const FoolsHatEnchantments = createSelector(selectDynamicFoolsHatEnchantments, (foolsHatEnchantments): All.Dynamic.FoolsHatEnchantments => Object.values(foolsHatEnchantments ?? {}))
    // export const GemsAndPreciousStones = createSelector(selectDynamicGemsAndPreciousStones, (gemsAndPreciousStones): GetAll.Dynamic.GemsAndPreciousStones => Object.values(gemsAndPreciousStones ?? {}))
    export const GeneralSpecialAbilities = createSelector(selectDynamicGeneralSpecialAbilities, (generalSpecialAbilities): All.Dynamic.GeneralSpecialAbilities => Object.values(generalSpecialAbilities ?? {}))
    export const GeodeRituals = createSelector(selectDynamicGeodeRituals, (geodeRituals): All.Dynamic.GeodeRituals => Object.values(geodeRituals ?? {}))
    // export const IlluminationLightSources = createSelector(selectDynamicIlluminationLightSources, (illuminationLightSources): GetAll.Dynamic.IlluminationLightSources => Object.values(illuminationLightSources ?? {}))
    // export const IlluminationRefillsAndSupplies = createSelector(selectDynamicIlluminationRefillsAndSupplies, (illuminationRefillsAndSupplies): GetAll.Dynamic.IlluminationRefillsAndSupplies => Object.values(illuminationRefillsAndSupplies ?? {}))
    export const InstrumentEnchantments = createSelector(selectDynamicInstrumentEnchantments, (instrumentEnchantments): All.Dynamic.InstrumentEnchantments => Object.values(instrumentEnchantments ?? {}))
    export const JesterTricks = createSelector(selectDynamicJesterTricks, (jesterTricks): All.Dynamic.JesterTricks => Object.values(jesterTricks ?? {}))
    // export const Jewelry = createSelector(selectDynamicJewelry, (jewelry): GetAll.Dynamic.Jewelry => Object.values(jewelry ?? {}))
    export const KarmaSpecialAbilities = createSelector(selectDynamicKarmaSpecialAbilities, (karmaSpecialAbilities): All.Dynamic.KarmaSpecialAbilities => Object.values(karmaSpecialAbilities ?? {}))
    export const Krallenkettenzauber = createSelector(selectDynamicKrallenkettenzauber, (krallenkettenzauber): All.Dynamic.Krallenkettenzauber => Object.values(krallenkettenzauber ?? {}))
    // export const Liebesspielzeuge = createSelector(selectDynamicLiebesspielzeuge, (liebesspielzeuge): GetAll.Dynamic.Liebesspielzeuge => Object.values(liebesspielzeuge ?? {}))
    export const LiturgicalChants = createSelector(selectDynamicLiturgicalChants, (liturgicalChants): All.Dynamic.LiturgicalChants => Object.values(liturgicalChants ?? {}))
    export const LiturgicalStyleSpecialAbilities = createSelector(selectDynamicLiturgicalStyleSpecialAbilities, (liturgicalStyleSpecialAbilities): All.Dynamic.LiturgicalStyleSpecialAbilities => Object.values(liturgicalStyleSpecialAbilities ?? {}))
    // export const LuxuryGoods = createSelector(selectDynamicLuxuryGoods, (luxuryGoods): GetAll.Dynamic.LuxuryGoods => Object.values(luxuryGoods ?? {}))
    export const LycantropicGifts = createSelector(selectDynamicLycantropicGifts, (lycantropicGifts): All.Dynamic.LycantropicGifts => Object.values(lycantropicGifts ?? {}))
    // export const MagicalArtifacts = createSelector(selectDynamicMagicalArtifacts, (magicalArtifacts): GetAll.Dynamic.MagicalArtifacts => Object.values(magicalArtifacts ?? {}))
    export const MagicalDances = createSelector(selectDynamicMagicalDances, (magicalDances): All.Dynamic.MagicalDances => Object.values(magicalDances ?? {}))
    export const MagicalMelodies = createSelector(selectDynamicMagicalMelodies, (magicalMelodies): All.Dynamic.MagicalMelodies => Object.values(magicalMelodies ?? {}))
    export const MagicalRunes = createSelector(selectDynamicMagicalRunes, (magicalRunes): All.Dynamic.MagicalRunes => Object.values(magicalRunes ?? {}))
    export const MagicalSigns = createSelector(selectDynamicMagicalSigns, (magicalSigns): All.Dynamic.MagicalSigns => Object.values(magicalSigns ?? {}))
    export const MagicalSpecialAbilities = createSelector(selectDynamicMagicalSpecialAbilities, (magicalSpecialAbilities): All.Dynamic.MagicalSpecialAbilities => Object.values(magicalSpecialAbilities ?? {}))
    export const MagicalTraditions = createSelector(selectDynamicMagicalTraditions, (magicalTraditions): All.Dynamic.MagicalTraditions => Object.values(magicalTraditions ?? {}))
    export const MagicStyleSpecialAbilities = createSelector(selectDynamicMagicStyleSpecialAbilities, (magicStyleSpecialAbilities): All.Dynamic.MagicStyleSpecialAbilities => Object.values(magicStyleSpecialAbilities ?? {}))
    // export const MetaConditions = createSelector(selectDynamicMetaConditions, (metaConditions): GetAll.Dynamic.MetaConditions => Object.values(metaConditions ?? {}))
    // export const MusicalInstruments = createSelector(selectDynamicMusicalInstruments, (musicalInstruments): GetAll.Dynamic.MusicalInstruments => Object.values(musicalInstruments ?? {}))
    export const OptionalRules = createSelector(selectDynamicOptionalRules, (optionalRules): All.Dynamic.OptionalRules => Object.values(optionalRules ?? {}))
    export const OrbEnchantments = createSelector(selectDynamicOrbEnchantments, (orbEnchantments): All.Dynamic.OrbEnchantments => Object.values(orbEnchantments ?? {}))
    // export const OrienteeringAids = createSelector(selectDynamicOrienteeringAids, (orienteeringAids): GetAll.Dynamic.OrienteeringAids => Object.values(orienteeringAids ?? {}))
    export const PactGifts = createSelector(selectDynamicPactGifts, (pactGifts): All.Dynamic.PactGifts => Object.values(pactGifts ?? {}))
    // export const PersonalityTraits = createSelector(selectDynamicPersonalityTraits, (personalityTraits): GetAll.Dynamic.PersonalityTraits => Object.values(personalityTraits ?? {}))
    // export const Poisons = createSelector(selectDynamicPoisons, (poisons): GetAll.Dynamic.Poisons => Object.values(poisons ?? {}))
    export const ProtectiveWardingCircleSpecialAbilities = createSelector(selectDynamicProtectiveWardingCircleSpecialAbilities, (protectiveWardingCircleSpecialAbilities): All.Dynamic.ProtectiveWardingCircleSpecialAbilities => Object.values(protectiveWardingCircleSpecialAbilities ?? {}))
    // export const Publications = createSelector(selectDynamicPublications, (publications): GetAll.Dynamic.Publications => Object.values(publications ?? {}))
    export const RangedCombatTechniques = createSelector(selectDynamicRangedCombatTechniques, (rangedCombatTechniques): All.Dynamic.RangedCombatTechniques => Object.values(rangedCombatTechniques ?? {}))
    export const RingEnchantments = createSelector(selectDynamicRingEnchantments, (ringEnchantments): All.Dynamic.RingEnchantments => Object.values(ringEnchantments ?? {}))
    export const Rituals = createSelector(selectDynamicRituals, (rituals): All.Dynamic.Rituals => Object.values(rituals ?? {}))
    // export const RopesAndChains = createSelector(selectDynamicRopesAndChains, (ropesAndChains): GetAll.Dynamic.RopesAndChains => Object.values(ropesAndChains ?? {}))
    export const Sermons = createSelector(selectDynamicSermons, (sermons): All.Dynamic.Sermons => Object.values(sermons ?? {}))
    export const SexSpecialAbilities = createSelector(selectDynamicSexSpecialAbilities, (sexSpecialAbilities): All.Dynamic.SexSpecialAbilities => Object.values(sexSpecialAbilities ?? {}))
    export const SickleRituals = createSelector(selectDynamicSickleRituals, (sickleRituals): All.Dynamic.SickleRituals => Object.values(sickleRituals ?? {}))
    export const SikaryanDrainSpecialAbilities = createSelector(selectDynamicSikaryanDrainSpecialAbilities, (sikaryanDrainSpecialAbilities): All.Dynamic.SikaryanDrainSpecialAbilities => Object.values(sikaryanDrainSpecialAbilities ?? {}))
    export const Skills = createSelector(selectDynamicSkills, (skills): All.Dynamic.Skills => Object.values(skills ?? {}))
    export const SkillStyleSpecialAbilities = createSelector(selectDynamicSkillStyleSpecialAbilities, (skillStyleSpecialAbilities): All.Dynamic.SkillStyleSpecialAbilities => Object.values(skillStyleSpecialAbilities ?? {}))
    export const Spells = createSelector(selectDynamicSpells, (spells): All.Dynamic.Spells => Object.values(spells ?? {}))
    export const SpellSwordEnchantments = createSelector(selectDynamicSpellSwordEnchantments, (spellSwordEnchantments): All.Dynamic.SpellSwordEnchantments => Object.values(spellSwordEnchantments ?? {}))
    export const StaffEnchantments = createSelector(selectDynamicStaffEnchantments, (staffEnchantments): All.Dynamic.StaffEnchantments => Object.values(staffEnchantments ?? {}))
    export const States = createSelector(selectDynamicStates, (states): All.Dynamic.States => Object.values(states ?? {}))
    // export const Stationary = createSelector(selectDynamicStationary, (stationary): GetAll.Dynamic.Stationary => Object.values(stationary ?? {}))
    // export const Talismans = createSelector(selectDynamicTalismans, (talismans): GetAll.Dynamic.Talismans => Object.values(talismans ?? {}))
    // export const ThievesTools = createSelector(selectDynamicThievesTools, (thievesTools): GetAll.Dynamic.ThievesTools => Object.values(thievesTools ?? {}))
    // export const ToolsOfTheTrade = createSelector(selectDynamicToolsOfTheTrade, (toolsOfTheTrade): GetAll.Dynamic.ToolsOfTheTrade => Object.values(toolsOfTheTrade ?? {}))
    export const ToyEnchantments = createSelector(selectDynamicToyEnchantments, (toyEnchantments): All.Dynamic.ToyEnchantments => Object.values(toyEnchantments ?? {}))
    // export const TravelGearAndTools = createSelector(selectDynamicTravelGearAndTools, (travelGearAndTools): GetAll.Dynamic.TravelGearAndTools => Object.values(travelGearAndTools ?? {}))
    export const Trinkhornzauber = createSelector(selectDynamicTrinkhornzauber, (trinkhornzauber): All.Dynamic.Trinkhornzauber => Object.values(trinkhornzauber ?? {}))
    export const VampiricGifts = createSelector(selectDynamicVampiricGifts, (vampiricGifts): All.Dynamic.VampiricGifts => Object.values(vampiricGifts ?? {}))
    // export const Vehicle s=createSelector(selectDynamicVehicle, (vehicle): GetAll.Dynamic.Vehicle => Object.values(vehicle ?? {}))
    export const Visions = createSelector(selectDynamicVisions, (visions): All.Dynamic.Visions => Object.values(visions ?? {}))
    export const WandEnchantments = createSelector(selectDynamicWandEnchantments, (wandEnchantments): All.Dynamic.WandEnchantments => Object.values(wandEnchantments ?? {}))
    // export const WeaponAccessories = createSelector(selectDynamicWeaponAccessories, (weaponAccessories): GetAll.Dynamic.WeaponAccessories => Object.values(weaponAccessories ?? {}))
    export const WeaponEnchantments = createSelector(selectDynamicWeaponEnchantments, (weaponEnchantments): All.Dynamic.WeaponEnchantments => Object.values(weaponEnchantments ?? {}))
    // export const Weapons = createSelector(selectDynamicWeapons, (weapons): GetAll.Dynamic.Weapons => Object.values(weapons ?? {}))
    export const ZibiljaRituals = createSelector(selectDynamicZibiljaRituals, (zibiljaRituals): All.Dynamic.ZibiljaRituals => Object.values(zibiljaRituals ?? {}))
  }
}
