import { createSelector } from "@reduxjs/toolkit"
import { filterApplyingRatedDependencies } from "../../shared/domain/dependencies/filterApplyingDependencies.ts"
import { checkMultipleDisjunctionPartsAreValid } from "../../shared/domain/prerequisites/disjunctionPrerequisiteMultipartValidation.ts"
import { selectDatabase } from "../slices/databaseSlice.ts"
import * as PrerequisiteCaps from "./prerequisiteSelectors.ts"

/**
 * Selects a filter function to filter unapplying dependencies of rated entries.
 */
export const selectFilterApplyingRatedDependencies = createSelector(
  selectDatabase,
  PrerequisiteCaps.selectCapabilitiesForActivatablePrerequisite,
  PrerequisiteCaps.selectCapabilitiesForAncestorBloodPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForBlessedTraditionPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForCommonSuggestedByRCPPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForCulturePrerequisite,
  PrerequisiteCaps.selectCapabilitiesForExternalEnhancementPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForInfluencePrerequisite,
  PrerequisiteCaps.selectCapabilitiesForMagicalTraditionPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForPactPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForPrimaryAttributePrerequisite,
  PrerequisiteCaps.selectCapabilitiesForPublicationPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForRacePrerequisite,
  PrerequisiteCaps.selectCapabilitiesForRatedMinimumNumberPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForRatedPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForRatedSumPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForRulePrerequisite,
  PrerequisiteCaps.selectCapabilitiesForSexPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForSexualCharacteristicPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForSocialStatusPrerequisite,
  PrerequisiteCaps.selectCapabilitiesForStatePrerequisite,
  PrerequisiteCaps.selectCapabilitiesForTextPrerequisite,
  (
    database,
    activatablePrerequisiteCapabilities,
    ancestorBloodPrerequisiteCapabilities,
    blessedTraditionPrerequisiteCapabilities,
    commonSuggestedByRCPPrerequisiteCapabilities,
    culturePrerequisiteCapabilities,
    externalEnhancementPrerequisiteCapabilities,
    influencePrerequisiteCapabilities,
    magicalTraditionPrerequisiteCapabilities,
    pactPrerequisiteCapabilities,
    primaryAttributePrerequisiteCapabilities,
    publicationPrerequisiteCapabilities,
    racePrerequisiteCapabilities,
    ratedMinimumNumberPrerequisiteCapabilities,
    ratedPrerequisiteCapabilities,
    ratedSumPrerequisiteCapabilities,
    rulePrerequisiteCapabilities,
    sexPrerequisiteCapabilities,
    sexualCharacteristicPrerequisiteCapabilities,
    socialStatusPrerequisiteCapabilities,
    statePrerequisiteCapabilities,
    textPrerequisiteCapabilities,
  ) =>
    filterApplyingRatedDependencies(
      checkMultipleDisjunctionPartsAreValid({
        getStaticDisadvantageById: id => database.disadvantages[id],
        getStaticGeneralSpecialAbilityById: id => database.generalSpecialAbilities[id],
        getStaticFatePointSpecialAbilityById: id => database.fatePointSpecialAbilities[id],
        getStaticCombatSpecialAbilityById: id => database.combatSpecialAbilities[id],
        getStaticMagicalSpecialAbilityById: id => database.magicalSpecialAbilities[id],
        getStaticStaffEnchantmentById: id => database.staffEnchantments[id],
        getStaticFamiliarSpecialAbilityById: id => database.familiarSpecialAbilities[id],
        getStaticKarmaSpecialAbilityById: id => database.karmaSpecialAbilities[id],
        getStaticProtectiveWardingCircleSpecialAbilityById: id =>
          database.protectiveWardingCircleSpecialAbilities[id],
        getStaticCombatStyleSpecialAbilityById: id => database.combatStyleSpecialAbilities[id],
        getStaticAdvancedCombatSpecialAbilityById: id =>
          database.advancedCombatSpecialAbilities[id],
        getStaticCommandSpecialAbilityById: id => database.commandSpecialAbilities[id],
        getStaticMagicStyleSpecialAbilityById: id => database.magicStyleSpecialAbilities[id],
        getStaticAdvancedMagicalSpecialAbilityById: id =>
          database.advancedMagicalSpecialAbilities[id],
        getStaticSpellSwordEnchantmentById: id => database.spellSwordEnchantments[id],
        getStaticDaggerRitualById: id => database.daggerRituals[id],
        getStaticInstrumentEnchantmentById: id => database.instrumentEnchantments[id],
        getStaticAttireEnchantmentById: id => database.attireEnchantments[id],
        getStaticOrbEnchantmentById: id => database.orbEnchantments[id],
        getStaticWandEnchantmentById: id => database.wandEnchantments[id],
        getStaticBrawlingSpecialAbilityById: id => database.brawlingSpecialAbilities[id],
        getStaticAncestorGlyphById: id => database.ancestorGlyphs[id],
        getStaticCeremonialItemSpecialAbilityById: id =>
          database.ceremonialItemSpecialAbilities[id],
        getStaticSermonById: id => database.sermons[id],
        getStaticLiturgicalStyleSpecialAbilityById: id =>
          database.liturgicalStyleSpecialAbilities[id],
        getStaticAdvancedKarmaSpecialAbilityById: id => database.advancedKarmaSpecialAbilities[id],
        getStaticVisionById: id => database.visions[id],
        getStaticMagicalTraditionById: id => database.magicalTraditions[id],
        getStaticBlessedTraditionById: id => database.blessedTraditions[id],
        getStaticPactGiftById: id => database.pactGifts[id],
        getStaticSikaryanDrainSpecialAbilityById: id => database.sikaryanDrainSpecialAbilities[id],
        getStaticLycantropicGiftById: id => database.lycantropicGifts[id],
        getStaticSkillStyleSpecialAbilityById: id => database.skillStyleSpecialAbilities[id],
        getStaticAdvancedSkillSpecialAbilityById: id => database.advancedSkillSpecialAbilities[id],
        getStaticArcaneOrbEnchantmentById: id => database.arcaneOrbEnchantments[id],
        getStaticCauldronEnchantmentById: id => database.cauldronEnchantments[id],
        getStaticFoolsHatEnchantmentById: id => database.foolsHatEnchantments[id],
        getStaticToyEnchantmentById: id => database.toyEnchantments[id],
        getStaticBowlEnchantmentById: id => database.bowlEnchantments[id],
        getStaticFatePointSexSpecialAbilityById: id => database.fatePointSexSpecialAbilities[id],
        getStaticSexSpecialAbilityById: id => database.sexSpecialAbilities[id],
        getStaticWeaponEnchantmentById: id => database.weaponEnchantments[id],
        getStaticSickleRitualById: id => database.sickleRituals[id],
        getStaticRingEnchantmentById: id => database.ringEnchantments[id],
        getStaticChronicleEnchantmentById: id => database.chronicleEnchantments[id],
        getStaticKrallenkettenzauberById: id => database.krallenkettenzauber[id],
        getStaticTrinkhornzauberById: id => database.trinkhornzauber[id],
        getStaticSpellById: id => database.spells[id],
        getStaticRitualById: id => database.rituals[id],
        getStaticLiturgicalChantById: id => database.liturgicalChants[id],
        getStaticCeremonyById: id => database.ceremonies[id],
        ...activatablePrerequisiteCapabilities,
        ...ancestorBloodPrerequisiteCapabilities,
        ...blessedTraditionPrerequisiteCapabilities,
        ...commonSuggestedByRCPPrerequisiteCapabilities,
        ...culturePrerequisiteCapabilities,
        ...externalEnhancementPrerequisiteCapabilities,
        ...influencePrerequisiteCapabilities,
        ...magicalTraditionPrerequisiteCapabilities,
        ...pactPrerequisiteCapabilities,
        ...primaryAttributePrerequisiteCapabilities,
        ...publicationPrerequisiteCapabilities,
        ...racePrerequisiteCapabilities,
        ...ratedMinimumNumberPrerequisiteCapabilities,
        ...ratedPrerequisiteCapabilities,
        ...ratedSumPrerequisiteCapabilities,
        ...rulePrerequisiteCapabilities,
        ...sexPrerequisiteCapabilities,
        ...sexualCharacteristicPrerequisiteCapabilities,
        ...socialStatusPrerequisiteCapabilities,
        ...statePrerequisiteCapabilities,
        ...textPrerequisiteCapabilities,
      }),
    ),
)
