export enum SkillGroup {
  Physical = 1,
  Social = 2,
  Nature = 3,
  Knowledge = 4,
  Craft = 5,
}

export enum CombatTechniqueGroup {
  Melee = 1,
  Ranged = 2,
}

export enum SpecialAbilityGroup {
  General = 1,
  Fate = 2,
  Combat = 3,
  Magical = 4,
  StaffEnchantments = 5,
  Witch = 6,
  Karma = 7,
  ProtectiveWardingCircles = 8,
  CombatStylesArmed = 9,
  CombatStylesUnarmed = 10,
  CombatExtended = 11,
  Commands = 12,
  MagicalStyles = 13,
  MagicalExtended = 14,
  Bannschwert = 15,
  Dolch = 16,
  Instrument = 17,
  Gewand = 18,
  Kugel = 19,
  Stecken = 20,
  Prügel = 21,
  Ahnenzeichen = 22,
  Zeremonialgegenstände = 23,
  Predigten = 24,
  BlessedStyles = 25,
  KarmaExtended = 26,
  Visionen = 27,
  MagicalTraditions = 28,
  BlessedTraditions = 29,
  Paktgeschenke = 30,
  Vampirismus = 31,
  Lykanthropie = 32,
  SkillStyles = 33,
  SkillExtended = 34,
  Magierkugel = 35,
  Hexenkessel = 36,
  Narrenkappe = 37,
  Schelmenspielzeug = 38,
  Alchimistenschale = 39,
  SexSchicksal = 40,
  Sex = 41,
  WaffenzauberAnimisten = 42,
  Sichelrituale = 43,
  Ringzauber = 44,
  Chronikzauber = 45,
}
