// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var PhaseId = {
  rcp: 1,
  creation: 2,
  inGame: 3
};

var ExperienceLevelId = {
  inexperienced: "EL_1",
  ordinary: "EL_2",
  experienced: "EL_3",
  competent: "EL_4",
  masterly: "EL_5",
  brilliant: "EL_6",
  legendary: "EL_7"
};

var RaceId = {
  humans: "R_1",
  elves: "R_2",
  halfElves: "R_3",
  dwarves: "R_4"
};

var CultureId = {
  gladeElves: "C_19",
  firnelves: "C_20",
  woodElves: "C_21",
  steppenelfen: "C_28"
};

var ProfessionId = {
  customProfession: "P_0"
};

var AttrId = {
  courage: "ATTR_1",
  sagacity: "ATTR_2",
  intuition: "ATTR_3",
  charisma: "ATTR_4",
  dexterity: "ATTR_5",
  agility: "ATTR_6",
  constitution: "ATTR_7",
  strength: "ATTR_8"
};

var DCId = {
  lifePoints: "LP",
  arcaneEnergy: "AE",
  karmaPoints: "KP",
  spirit: "SPI",
  toughness: "TOU",
  dodge: "DO",
  initiative: "INI",
  movement: "MOV",
  woundThreshold: "WT"
};

function fromInt(id) {
  switch (id) {
    case 4 :
        return /* Aptitude */0;
    case 9 :
        return /* Nimble */1;
    case 12 :
        return /* Blessed */2;
    case 14 :
        return /* Luck */3;
    case 16 :
        return /* ExceptionalSkill */4;
    case 17 :
        return /* ExceptionalCombatTechnique */5;
    case 23 :
        return /* IncreasedAstralPower */6;
    case 24 :
        return /* IncreasedKarmaPoints */7;
    case 25 :
        return /* IncreasedLifePoints */8;
    case 26 :
        return /* IncreasedSpirit */9;
    case 27 :
        return /* IncreasedToughness */10;
    case 28 :
        return /* ImmunityToPoison */11;
    case 29 :
        return /* ImmunityToDisease */12;
    case 32 :
        return /* MagicalAttunement */13;
    case 36 :
        return /* Rich */14;
    case 40 :
        return /* SociallyAdaptable */15;
    case 46 :
        return /* InspireConfidence */16;
    case 47 :
        return /* WeaponAptitude */17;
    case 50 :
        return /* Spellcaster */18;
    case 54 :
        return /* Unyielding */19;
    case 58 :
        return /* LargeSpellSelection */20;
    case 68 :
        return /* HatredOf */21;
    case 77 :
        return /* Prediger */22;
    case 78 :
        return /* Visionaer */23;
    case 79 :
        return /* ZahlreichePredigten */24;
    case 80 :
        return /* ZahlreicheVisionen */25;
    case 92 :
        return /* LeichterGang */26;
    case 5 :
    case 6 :
    case 7 :
    case 8 :
    case 10 :
    case 11 :
    case 13 :
    case 15 :
    case 18 :
    case 19 :
    case 20 :
    case 21 :
    case 22 :
    case 30 :
    case 31 :
    case 33 :
    case 34 :
    case 35 :
    case 37 :
    case 38 :
    case 39 :
    case 41 :
    case 42 :
    case 43 :
    case 44 :
    case 45 :
    case 48 :
    case 49 :
    case 51 :
    case 52 :
    case 53 :
    case 55 :
    case 56 :
    case 57 :
    case 59 :
    case 60 :
    case 61 :
    case 62 :
    case 63 :
    case 64 :
    case 65 :
    case 66 :
    case 67 :
    case 69 :
    case 70 :
    case 71 :
    case 72 :
    case 73 :
    case 74 :
    case 75 :
    case 76 :
    case 81 :
    case 82 :
    case 83 :
    case 84 :
    case 85 :
    case 86 :
    case 87 :
    case 88 :
    case 89 :
    case 90 :
    case 91 :
    case 93 :
    case 94 :
    case 95 :
    case 96 :
    case 97 :
    case 98 :
        return /* Other */[id];
    case 99 :
        return /* Einkommen */27;
    default:
      return /* Other */[id];
  }
}

function toInt(id) {
  if (typeof id === "number") {
    switch (id) {
      case /* Aptitude */0 :
          return 4;
      case /* Nimble */1 :
          return 9;
      case /* Blessed */2 :
          return 12;
      case /* Luck */3 :
          return 14;
      case /* ExceptionalSkill */4 :
          return 16;
      case /* ExceptionalCombatTechnique */5 :
          return 17;
      case /* IncreasedAstralPower */6 :
          return 23;
      case /* IncreasedKarmaPoints */7 :
          return 24;
      case /* IncreasedLifePoints */8 :
          return 25;
      case /* IncreasedSpirit */9 :
          return 26;
      case /* IncreasedToughness */10 :
          return 27;
      case /* ImmunityToPoison */11 :
          return 28;
      case /* ImmunityToDisease */12 :
          return 29;
      case /* MagicalAttunement */13 :
          return 32;
      case /* Rich */14 :
          return 36;
      case /* SociallyAdaptable */15 :
          return 40;
      case /* InspireConfidence */16 :
          return 46;
      case /* WeaponAptitude */17 :
          return 47;
      case /* Spellcaster */18 :
          return 50;
      case /* Unyielding */19 :
          return 54;
      case /* LargeSpellSelection */20 :
          return 58;
      case /* HatredOf */21 :
          return 68;
      case /* Prediger */22 :
          return 77;
      case /* Visionaer */23 :
          return 78;
      case /* ZahlreichePredigten */24 :
          return 79;
      case /* ZahlreicheVisionen */25 :
          return 80;
      case /* LeichterGang */26 :
          return 92;
      case /* Einkommen */27 :
          return 99;
      
    }
  } else {
    return id[0];
  }
}

var AdvantageId = {
  fromInt: fromInt,
  toInt: toInt,
  aptitude: "ADV_4",
  nimble: "ADV_9",
  blessed: "ADV_12",
  luck: "ADV_14",
  exceptionalSkill: "ADV_16",
  exceptionalCombatTechnique: "ADV_17",
  increasedAstralPower: "ADV_23",
  increasedKarmaPoints: "ADV_24",
  increasedLifePoints: "ADV_25",
  increasedSpirit: "ADV_26",
  increasedToughness: "ADV_27",
  immunityToPoison: "ADV_28",
  immunityToDisease: "ADV_29",
  magicalAttunement: "ADV_32",
  rich: "ADV_36",
  sociallyAdaptable: "ADV_40",
  inspireConfidence: "ADV_46",
  weaponAptitude: "ADV_47",
  spellcaster: "ADV_50",
  unyielding: "ADV_54",
  largeSpellSelection: "ADV_58",
  hatredOf: "ADV_68",
  prediger: "ADV_77",
  visionaer: "ADV_78",
  zahlreichePredigten: "ADV_79",
  zahlreicheVisionen: "ADV_80",
  leichterGang: "ADV_92",
  einkommen: "ADV_99"
};

var DisadvantageId = {
  afraidOf: "DISADV_1",
  poor: "DISADV_2",
  slow: "DISADV_4",
  noFlyingBalm: "DISADV_17",
  noFamiliar: "DISADV_18",
  magicalRestriction: "DISADV_24",
  decreasedArcanePower: "DISADV_26",
  decreasedKarmaPoints: "DISADV_27",
  decreasedLifePoints: "DISADV_28",
  decreasedSpirit: "DISADV_29",
  decreasedToughness: "DISADV_30",
  badLuck: "DISADV_31",
  personalityFlaw: "DISADV_33",
  principles: "DISADV_34",
  badHabit: "DISADV_36",
  negativeTrait: "DISADV_37",
  stigma: "DISADV_45",
  deaf: "DISADV_47",
  incompetent: "DISADV_48",
  obligations: "DISADV_50",
  maimed: "DISADV_51",
  brittleBones: "DISADV_56",
  smallSpellSelection: "DISADV_59",
  wenigePredigten: "DISADV_72",
  wenigeVisionen: "DISADV_73"
};

var SkillId = {
  flying: "TAL_1",
  gaukelei: "TAL_2",
  climbing: "TAL_3",
  bodyControl: "TAL_4",
  featOfStrength: "TAL_5",
  riding: "TAL_6",
  swimming: "TAL_7",
  selfControl: "TAL_8",
  singing: "TAL_9",
  perception: "TAL_10",
  dancing: "TAL_11",
  pickpocket: "TAL_12",
  stealth: "TAL_13",
  carousing: "TAL_14",
  persuasion: "TAL_15",
  seduction: "TAL_16",
  intimidation: "TAL_17",
  etiquette: "TAL_18",
  streetwise: "TAL_19",
  empathy: "TAL_20",
  fastTalk: "TAL_21",
  disguise: "TAL_22",
  willpower: "TAL_23",
  tracking: "TAL_24",
  ropes: "TAL_25",
  fishing: "TAL_26",
  orienting: "TAL_27",
  plantLore: "TAL_28",
  animalLore: "TAL_29",
  survival: "TAL_30",
  gambling: "TAL_31",
  geography: "TAL_32",
  history: "TAL_33",
  religions: "TAL_34",
  warfare: "TAL_35",
  magicalLore: "TAL_36",
  mechanics: "TAL_37",
  math: "TAL_38",
  law: "TAL_39",
  mythsAndLegends: "TAL_40",
  sphereLore: "TAL_41",
  astronomy: "TAL_42",
  alchemy: "TAL_43",
  sailing: "TAL_44",
  driving: "TAL_45",
  commerce: "TAL_46",
  treatPoison: "TAL_47",
  treatDisease: "TAL_48",
  treatSoul: "TAL_49",
  treatWounds: "TAL_50",
  woodworking: "TAL_51",
  prepareFood: "TAL_52",
  leatherworking: "TAL_53",
  artisticAbility: "TAL_54",
  metalworking: "TAL_55",
  music: "TAL_56",
  pickLocks: "TAL_57",
  earthencraft: "TAL_58",
  clothworking: "TAL_59"
};

var CombatTechniqueId = {
  crossbows: "CT_1",
  bows: "CT_2",
  daggers: "CT_3",
  fencingWeapons: "CT_4",
  impactWeapons: "CT_5",
  chainWeapons: "CT_6",
  lances: "CT_7",
  brawling: "CT_9",
  shields: "CT_10",
  slings: "CT_11",
  swords: "CT_12",
  polearms: "CT_13",
  thrownWeapons: "CT_14",
  twoHandedImpactWeapons: "CT_15",
  twoHandedSwords: "CT_16",
  spittingFire: "CT_17",
  blowguns: "CT_18",
  discuses: "CT_19",
  faecher: "CT_20",
  spiesswaffen: "CT_21"
};

var SpecialAbilityId = {
  skillSpecialization: "SA_9",
  terrainKnowledge: "SA_12",
  craftInstruments: "SA_17",
  hunter: "SA_18",
  areaKnowledge: "SA_22",
  literacy: "SA_27",
  language: "SA_29",
  combatReflexes: "SA_51",
  improvedDodge: "SA_64",
  traditionGuildMages: 70,
  propertyKnowledge: "SA_72",
  propertyFocus: "SA_81",
  aspectKnowledge: "SA_87",
  traditionChurchOfPraios: "SA_86",
  feuerschlucker: "SA_109",
  combatStyleCombination: "SA_164",
  adaptionZauber: "SA_231",
  exorzist: "SA_240",
  favoriteSpellwork: "SA_250",
  traditionWitches: "SA_255",
  magicStyleCombination: "SA_266",
  harmoniezauberei: "SA_296",
  matrixzauberei: "SA_303",
  traditionElves: "SA_345",
  traditionDruids: "SA_346",
  spellEnhancement: 414,
  forschungsgebiet: "SA_472",
  expertenwissen: "SA_473",
  wissensdurst: "SA_531",
  recherchegespuer: "SA_533",
  predigtDerGemeinschaft: "SA_544",
  predigtDerZuversicht: "SA_545",
  predigtDesGottvertrauens: "SA_546",
  predigtDesWohlgefallens: "SA_547",
  predigtWiderMissgeschicke: "SA_548",
  visionDerBestimmung: "SA_549",
  visionDerEntrueckung: "SA_550",
  visionDerGottheit: "SA_551",
  visionDesSchicksals: "SA_552",
  visionDesWahrenGlaubens: "SA_553",
  hoheWeihe: "SA_563",
  lieblingsliturgie: "SA_569",
  zugvoegel: "SA_623",
  jaegerinnenDerWeissenMaid: "SA_625",
  anhaengerDesGueldenen: "SA_632",
  gebieterDesAspekts: "SA_639",
  chantEnhancement: 663,
  dunklesAbbildDerBuendnisgabe: "SA_667",
  traditionIllusionist: "SA_676",
  traditionArcaneBard: "SA_677",
  traditionArcaneDancer: "SA_678",
  traditionIntuitiveMage: "SA_679",
  traditionSavant: "SA_680",
  traditionQabalyaMage: "SA_681",
  traditionChurchOfRondra: "SA_682",
  traditionChurchOfBoron: "SA_683",
  traditionChurchOfHesinde: "SA_684",
  traditionChurchOfPhex: "SA_685",
  traditionChurchOfPeraine: "SA_686",
  traditionChurchOfEfferd: "SA_687",
  traditionChurchOfTravia: "SA_688",
  traditionChurchOfFirun: "SA_689",
  traditionChurchOfTsa: "SA_690",
  traditionChurchOfIngerimm: "SA_691",
  traditionChurchOfRahja: "SA_692",
  traditionCultOfTheNamelessOne: "SA_693",
  traditionChurchOfAves: "SA_694",
  traditionChurchOfIfirn: "SA_695",
  traditionChurchOfKor: "SA_696",
  traditionChurchOfNandus: "SA_697",
  traditionChurchOfSwafnir: "SA_698",
  languageSpecializations: "SA_699",
  traditionSchelme: "SA_726",
  traditionZauberalchimisten: "SA_750",
  grosseMeditation: "SA_772",
  imitationszauberei: "SA_775",
  kraftliniennutzung: "SA_781",
  scholarDerHalleDesLebensZuNorburg: "SA_802",
  scholarDesKreisesDerEinfuehlung: "SA_808",
  madaschwesternStil: "SA_821",
  garetherGossenStil: "SA_901",
  wegDerGelehrten: "SA_1040",
  traditionCultOfNuminoru: "SA_1049",
  wegDerKuenstlerin: "SA_1069",
  wegDerSchreiberin: "SA_1075",
  fachwissen: "SA_1100",
  handwerkskunst: "SA_1108",
  kindDerNatur: "SA_1110",
  koerperlichesGeschick: "SA_1112",
  sozialeKompetenz: "SA_1123",
  universalgenie: "SA_1127",
  scholarDesMagierkollegsZuHoningen: "SA_1147",
  traditionAnimisten: "SA_1221",
  traditionGeoden: "SA_1255",
  traditionZibilijas: "SA_1293",
  zaubervariabilitaet: "SA_1391",
  traditionBrobimGeoden: "SA_1438"
};

var SocialStatusId = {
  notFree: 1,
  free: 2,
  lesserNoble: 3,
  noble: 4,
  aristocracy: 5
};

var OptionalRuleId = {
  maximumAttributeScores: "OR_8",
  languageSpecialization: "OR_15",
  higherDefenseStats: "OR_17"
};

var ConditionId = {
  sikaryanVerlust: "COND_11",
  daemonischeAuszehrung: "COND_14"
};

exports.PhaseId = PhaseId;
exports.ExperienceLevelId = ExperienceLevelId;
exports.RaceId = RaceId;
exports.CultureId = CultureId;
exports.ProfessionId = ProfessionId;
exports.AttrId = AttrId;
exports.DCId = DCId;
exports.AdvantageId = AdvantageId;
exports.DisadvantageId = DisadvantageId;
exports.SkillId = SkillId;
exports.CombatTechniqueId = CombatTechniqueId;
exports.SpecialAbilityId = SpecialAbilityId;
exports.SocialStatusId = SocialStatusId;
exports.OptionalRuleId = OptionalRuleId;
exports.ConditionId = ConditionId;
/* No side effect */
