/**
 * This file provides several helper functions for working with `Activatable`s.
 *
 * @file src/utils/activatableConvertUtils.ts
 * @author Lukas Obermann
 * @since 1.1.0
 */

import { pipe } from "ramda";
import { fmap } from "../../../Data/Functor";
import { append, elemF, empty, imap, List } from "../../../Data/List";
import { alt, guard, isJust, Nothing, or, then } from "../../../Data/Maybe";
import { foldr } from "../../../Data/OrderedMap";
import { mergeSafeR2, Record } from "../../../Data/Record";
import { ActivatableActivationOptions } from "../../Models/Actions/ActivatableActivationOptions";
import { ActivatableDependent } from "../../Models/ActiveEntries/ActivatableDependent";
import { ActiveObject } from "../../Models/ActiveEntries/ActiveObject";
import { ActiveObjectWithId } from "../../Models/ActiveEntries/ActiveObjectWithId";

const { id, active } = ActivatableDependent.A
const { sid, sid2, tier, cost } = ActiveObject.A
const { selectOptionId1, selectOptionId2, input, level, customCost } =
  ActivatableActivationOptions.A

/**
 * Converts the object generated by the list item to an object that can be
 * inserted into an array of ActiveObjects.
 * @param obj The entry for which you want to convert the object.
 * @param activate The object generated by the list item.
 */
export const convertUIStateToActiveObject =
  (activate: Record<ActivatableActivationOptions>): Record<ActiveObject> =>
    id (activate) === "ADV_68"
    ? ActiveObject ({
        sid: selectOptionId1 (activate),
        sid2: input (activate),
        cost: customCost (activate),
      })
    : id (activate) === "DISADV_33"
    ? ActiveObject ({
        sid: selectOptionId1 (activate),
        sid2: or (fmap (elemF (List<number | string> (7, 8)))
                       (selectOptionId1 (activate)))
          ? input (activate)
          : Nothing,
        cost: customCost (activate),
      })
    : id (activate) === "SA_9"
    ? ActiveObject ({
        sid: selectOptionId1 (activate),
        sid2: alt<number | string> (input (activate))
                                   (selectOptionId2 (activate)),
        cost: customCost (activate),
      })
    : ActiveObject ({
        sid: alt<number | string> (input (activate))
                                  (selectOptionId1 (activate)),
        sid2: then (guard (isJust (input (activate))
                           || isJust (selectOptionId1 (activate))))
                                    (selectOptionId2 (activate)),
        tier: level (activate),
        cost: customCost (activate),
      })

/**
 * Generates a list of ActiveObjects based on the given instance.
 */
export const convertActivatableToArray =
  (x: Record<ActivatableDependent>) =>
    pipe (
           active,
           imap (
             index => e => ActiveObjectWithId ({
                                               id: id (x),
                                               index,
                                               sid: sid (e),
                                               sid2: sid2 (e),
                                               tier: tier (e),
                                               cost: cost (e),
                                             })
           )
         )
         (x)

/**
 * Get all active items in an array.
 * @param state A state slice.
 */
export const getActiveFromState =
  foldr (pipe (convertActivatableToArray, append)) (empty)

export interface ActiveObjectAny extends ActiveObject {
  [key: string]: any
}

/**
 * Returns only `sid`, `sid2` and `tier` property of passed `ActiveObject`.
 * @param activeObject
 */
export const getActiveObjectCore =
  (x: Record<ActiveObjectAny>): Record<ActiveObject> =>
    mergeSafeR2<ActiveObject> (x) (ActiveObject.default)
