function keyMirror<T>(data: T): { [K in keyof T]: K; } {
	const newData = {} as { [K in keyof T]: K; };
	for (const constant in data) {
		if (data.hasOwnProperty(constant)) {
			newData[constant] = constant;
		}
	}
	return newData;
}

export type RECEIVE_DATA_TABLES = 'RECEIVE_DATA_TABLES';
export const RECEIVE_DATA_TABLES = 'RECEIVE_DATA_TABLES';

export type SET_SECTION = 'SET_SECTION';
export const SET_SECTION = 'SET_SECTION';
export type SET_TAB = 'SET_TAB';
export const SET_TAB = 'SET_TAB';

export type REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export type RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export type REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export type RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export type REQUEST_REGISTRATION = 'REQUEST_REGISTRATION';
export const REQUEST_REGISTRATION = 'REQUEST_REGISTRATION';

export type SET_HEROLIST_VISIBILITY_FILTER = 'SET_HEROLIST_VISIBILITY_FILTER';
export const SET_HEROLIST_VISIBILITY_FILTER = 'SET_HEROLIST_VISIBILITY_FILTER';
export type SET_HEROLIST_SORT_ORDER = 'SET_HEROLIST_SORT_ORDER';
export const SET_HEROLIST_SORT_ORDER = 'SET_HEROLIST_SORT_ORDER';
export type REQUEST_HEROLIST = 'REQUEST_HEROLIST';
export const REQUEST_HEROLIST = 'REQUEST_HEROLIST';
export type RECEIVE_HEROLIST = 'RECEIVE_HEROLIST';
export const RECEIVE_HEROLIST = 'RECEIVE_HEROLIST';

export type REQUEST_HERO_DATA = 'REQUEST_HERO_DATA';
export const REQUEST_HERO_DATA = 'REQUEST_HERO_DATA';
export type RECEIVE_HERO_DATA = 'RECEIVE_HERO_DATA';
export const RECEIVE_HERO_DATA = 'RECEIVE_HERO_DATA';

export type SELECT_RACE = 'SELECT_RACE';
export const SELECT_RACE = 'SELECT_RACE';
export type SET_RACES_SORT_ORDER = 'SET_RACES_SORT_ORDER';
export const SET_RACES_SORT_ORDER = 'SET_RACES_SORT_ORDER';
export type SWITCH_RACE_VALUE_VISIBILITY = 'SWITCH_RACE_VALUE_VISIBILITY';
export const SWITCH_RACE_VALUE_VISIBILITY = 'SWITCH_RACE_VALUE_VISIBILITY';

export type SET_TALENTS_SORT_ORDER = 'SET_TALENTS_SORT_ORDER';
export const SET_TALENTS_SORT_ORDER = 'SET_TALENTS_SORT_ORDER';

export const ATS = keyMirror({

	// ServerActions
	RECEIVE_RAW_LISTS: null,

	// WaitStore
	WAIT_START: null,
	WAIT_END: null,

	// TabStore
	SHOW_TAB_SECTION: null,
	SHOW_TAB: null,

	// AuthStore
	RECEIVE_ACCOUNT: null,
	UPDATE_USERNAME: null,
	LOGOUT_SUCCESS: null,
	CLEAR_ACCOUNT: null,
	ACCOUNTNAME_CHANGE_SUCCESS: null,
	PASSWORD_CHANGE_SUCCESS: null,

	// Registration
	REGISTRATION_SUCCESS: null,

	// PaneStore
	HEROES_SHOW: null,
	HEROES_HIDE: null,
	COLLAPSE_HEROES: null,

	// HerolistStore
	RECEIVE_RAW_HEROLIST: null,
	SEARCH_HEROLIST: null,
	FILTER_HEROLIST: null,
	SORT_HEROLIST: null,
	CHANGE_HEROLIST_VIEW: null,
	CREATE_NEW_HERO: null,
	RECEIVE_HERO: null,

	// ProfileStore
	UPDATE_HERO_NAME: null,
	UPDATE_HERO_AVATAR: null,
	UPDATE_FAMILY: null,
	UPDATE_PLACEOFBIRTH: null,
	UPDATE_DATEOFBIRTH: null,
	UPDATE_AGE: null,
	UPDATE_HAIRCOLOR: null,
	UPDATE_EYECOLOR: null,
	UPDATE_SIZE: null,
	UPDATE_WEIGHT: null,
	UPDATE_TITLE: null,
	UPDATE_SOCIALSTATUS: null,
	UPDATE_CHARACTERISTICS: null,
	UPDATE_OTHERINFO: null,
	REROLL_HAIRCOLOR: null,
	REROLL_EYECOLOR: null,
	REROLL_SIZE: null,
	REROLL_WEIGHT: null,

	UNLOAD_HERO: null,
	CLEAR_HERO: null,
	SAVE_HERO_SUCCESS: null,

	// PhaseStore
	FINALIZE_CHARACTER_CREATION: null,

	// APStore
	ADD_ADVENTURE_POINTS: null,

	// RaceStore
	SELECT_RACE: null,
	FILTER_RACES: null,
	SORT_RACES: null,
	CHANGE_RACE_VALUE_VISIBILITY: null,

	// CultureStore
	SELECT_CULTURE: null,
	FILTER_CULTURES: null,
	SORT_CULTURES: null,
	CHANGE_CULTURE_VALUE_VISIBILITY: null,
	CHANGE_CULTURE_VIEW: null,
	CHANGE_CULTURE_PACKAGE: null,
	CHANGE_CULTURE_LITERACY: null,

	// ProfessionStore
	SELECT_PROFESSION: null,
	FILTER_PROFESSIONS: null,
	SORT_PROFESSIONS: null,
	CHANGE_PROFESSION_VIEW: null,
	ASSIGN_RCP_ENTRIES: null,

	// ProfessionVariantStore
	SELECT_PROFESSION_VARIANT: null,

	// AttributeStore
	ADD_ATTRIBUTE_POINT: null,
	REMOVE_ATTRIBUTE_POINT: null,
	ADD_MAX_ENERGY_POINT: null,

	// DisAdvStore
	FILTER_DISADV: null,
	CHANGE_DISADV_RATING: null,
	ACTIVATE_DISADV: null,
	DEACTIVATE_DISADV: null,
	UPDATE_DISADV_TIER: null,

	// TalentsStore
	FILTER_TALENTS: null,
	SORT_TALENTS: null,
	CHANGE_TALENT_RATING: null,
	ADD_TALENT_POINT: null,
	REMOVE_TALENT_POINT: null,

	// CombatTechniquesStore
	FILTER_COMBATTECHNIQUES: null,
	SORT_COMBATTECHNIQUES: null,
	ADD_COMBATTECHNIQUE_POINT: null,
	REMOVE_COMBATTECHNIQUE_POINT: null,

	// SpellsStore
	FILTER_SPELLS: null,
	SORT_SPELLS: null,
	UPDATE_SPELL_VIEW: null,
	ACTIVATE_SPELL: null,
	DEACTIVATE_SPELL: null,
	ADD_SPELL_POINT: null,
	REMOVE_SPELL_POINT: null,

	// LiturgiesStore
	FILTER_LITURGIES: null,
	SORT_LITURGIES: null,
	UPDATE_LITURGY_VIEW: null,
	ACTIVATE_LITURGY: null,
	DEACTIVATE_LITURGY: null,
	ADD_LITURGY_POINT: null,
	REMOVE_LITURGY_POINT: null,

	// SpecialAbilitiesStore
	FILTER_SPECIALABILITIES: null,
	SORT_SPECIALABILITIES: null,
	UPDATE_SPECIALABILITY_VIEW: null,
	ACTIVATE_SPECIALABILITY: null,
	DEACTIVATE_SPECIALABILITY: null,
	UPDATE_SPECIALABILITY_TIER: null,

	// InventoryStore
	FILTER_ITEMS: null,
	SORT_ITEMS: null,
	ADD_ITEM: null,
	SAVE_ITEM: null,
	REMOVE_ITEM: null,

	// GroupsStore
	SHOW_MASTER_REQUESTED_LIST: null,
	HIDE_MASTER_REQUESTED_LIST: null,

	// InGameStore
	LOAD_RAW_INGAME_DATA: null,
	INGAME_PREVIOUS_PHASE: null,
	INGAME_NEXT_PHASE: null,
	UPDATE_INGAME_CAST: null,
	CANCEL_INGAME_CAST: null,
	INGAME_USE_ENDURANCE: null,
	INGAME_USE_ACTION: null,
	INGAME_USE_FREE_ACTION: null,
	INGAME_ACTIVATE_FIGHTER: null,
	INGAME_DEACTIVATE_FIGHTER: null,
	INGAME_EDIT_START: null,
	INGAME_EDIT_UPDATE_VALUE: null,
	INGAME_EDIT_UPDATE_CAST_VALUE: null,
	INGAME_EDIT_UPDATE_DUPLICATE_VALUE: null,
	INGAME_EDIT_END: null,
	INGAME_ADD_FIGHTER: null,
	INGAME_DUPLICATE_FIGHTER: null,
	INGAME_REMOVE_FIGHTER: null,
	INGAME_RESET_PHASES: null,
	INGAME_RESET_HEALTH: null,
	INGAME_RESET_ALL: null,
	INGAME_UPDATE_ONLINE_LINK: null,
	INGAME_SAVE: null,
	INGAME_SWITCH_OPTION: null
});

export default ATS;
