type ADVANTAGES = 'ADVANTAGES';
type ATTRIBUTES = 'ATTRIBUTES';
type COMBAT_TECHNIQUES = 'COMBAT_TECHNIQUES';
type CULTURES = 'CULTURES';
type DISADVANTAGES = 'DISADVANTAGES';
type LITURGIES = 'LITURGIES';
type PROFESSION_VARIANTS = 'PROFESSION_VARIANTS';
type PROFESSIONS = 'PROFESSIONS';
type RACES = 'RACES';
type SPECIAL_ABILITIES = 'SPECIAL_ABILITIES';
type SPELLS = 'SPELLS';
type TALENTS = 'TALENTS';

type Category = ADVANTAGES | ATTRIBUTES | COMBAT_TECHNIQUES | CULTURES | DISADVANTAGES | LITURGIES | PROFESSION_VARIANTS | PROFESSIONS | RACES | SPECIAL_ABILITIES | SPELLS | TALENTS;
