export enum Categories {
  ADVANTAGES = 'ADVANTAGES',
  ATTRIBUTES = 'ATTRIBUTES',
  BLESSINGS = 'BLESSINGS',
  CANTRIPS = 'CANTRIPS',
  COMBAT_TECHNIQUES = 'COMBAT_TECHNIQUES',
  CULTURES = 'CULTURES',
  DISADVANTAGES = 'DISADVANTAGES',
  LITURGIES = 'LITURGIES',
  PROFESSION_VARIANTS = 'PROFESSION_VARIANTS',
  PROFESSIONS = 'PROFESSIONS',
  RACE_VARIANTS = 'RACE_VARIANTS',
  RACES = 'RACES',
  SPECIAL_ABILITIES = 'SPECIAL_ABILITIES',
  SPELLS = 'SPELLS',
  TALENTS = 'TALENTS',
}

export type ACTIVATABLE =
  Categories.ADVANTAGES |
  Categories.DISADVANTAGES |
  Categories.SPECIAL_ABILITIES;

export type CategoryWithGroups =
  Categories.COMBAT_TECHNIQUES |
  Categories.LITURGIES |
  Categories.SPECIAL_ABILITIES |
  Categories.SPELLS |
  Categories.TALENTS;
