// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var ndash = "\u2013";

var mdash = "\u2014";

var minus = "\u2212";

var nobr = "\u2060";

var nbsp = "\u00A0";

var plusmn = "\u00B1";

var closeIcon = "\uE5CD";

exports.ndash = ndash;
exports.mdash = mdash;
exports.minus = minus;
exports.nobr = nobr;
exports.nbsp = nbsp;
exports.plusmn = plusmn;
exports.closeIcon = closeIcon;
/* No side effect */
