// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Ley_List$OptolithClient from "../../Data/Ley_List.bs.js";
import * as Ley_Option$OptolithClient from "../../Data/Ley_Option.bs.js";

function isActive(x) {
  return Ley_List$OptolithClient.Extra.notNull(x.active);
}

function isActiveM(param) {
  return Ley_Option$OptolithClient.option(false, isActive, param);
}

function name(x) {
  return x[0].name;
}

function selectOptions(x) {
  switch (x.tag | 0) {
    case /* Advantage */0 :
    case /* Disadvantage */1 :
        return x[0].selectOptions;
    case /* SpecialAbility */2 :
        return x[0].selectOptions;
    
  }
}

function input(x) {
  switch (x.tag | 0) {
    case /* Advantage */0 :
    case /* Disadvantage */1 :
        return x[0].input;
    case /* SpecialAbility */2 :
        return x[0].input;
    
  }
}

function apValue(x) {
  switch (x.tag | 0) {
    case /* Advantage */0 :
    case /* Disadvantage */1 :
        return x[0].apValue;
    case /* SpecialAbility */2 :
        return x[0].apValue;
    
  }
}

export {
  isActive ,
  isActiveM ,
  name ,
  selectOptions ,
  input ,
  apValue ,
  
}
/* No side effect */
