// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as IO$OptolithClient from "../../System/IO.bs.js";
import * as Yaml_Raw$OptolithClient from "./Yaml_Raw.bs.js";
import * as Exception$OptolithClient from "../../Control/Exception.bs.js";
import * as Yaml_Decode$OptolithClient from "./Yaml_Decode.bs.js";

function parseStaticData(locale) {
  console.time("parseStaticData");
  return Exception$OptolithClient.handleE(IO$OptolithClient.Functor.$less$amp$great(Yaml_Raw$OptolithClient.getStaticData(locale), (function (yamlData) {
                    var res = Yaml_Decode$OptolithClient.decode(locale, yamlData);
                    console.log("Parsing static data done!");
                    console.timeEnd("parseStaticData");
                    return res;
                  })));
}

var Decode;

var Integrity;

var Raw;

var Zip;

export {
  Decode ,
  Integrity ,
  Raw ,
  Zip ,
  parseStaticData ,
  
}
/* IO-OptolithClient Not a pure module */
