// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Overlay$OptolithClient = require("./Overlay.bs.js");
var Ley_List$OptolithClient = require("../../../Data/Ley_List.bs.js");
var ClassNames$OptolithClient = require("../../../Utilities/ClassNames.bs.js");
var ReactUtils$OptolithClient = require("../../../Utilities/ReactUtils.bs.js");

function ActionSheet$Button(Props) {
  var label = Props.label;
  var value = Props.value;
  var style = Props.style;
  var disabled = Props.disabled;
  var onClick = Props.onClick;
  var handleClick = React.useCallback((function (param) {
          if (disabled) {
            return Curry._1(onClick, value);
          }
          
        }), [
        value,
        disabled,
        onClick
      ]);
  return React.createElement("button", {
              className: ClassNames$OptolithClient.fold({
                    hd: ClassNames$OptolithClient.cond("disabled", disabled),
                    tl: {
                      hd: ClassNames$OptolithClient.cond("destructive", style === /* Destructive */1),
                      tl: /* [] */0
                    }
                  }),
              type: "button",
              onClick: handleClick
            }, ReactUtils$OptolithClient.s(label));
}

var Button = {
  make: ActionSheet$Button
};

function ActionSheet(Props) {
  var description = Props.description;
  var buttons = Props.buttons;
  var isOpen = Props.isOpen;
  var onClick = Props.onClick;
  var onClose = Props.onClose;
  var cancelLabel = Props.cancelLabel;
  return React.createElement(Overlay$OptolithClient.make, {
              baseClassName: "actionsheet",
              children: null,
              isOpen: isOpen,
              onBackdrop: onClose
            }, React.createElement("div", {
                  className: "buttons"
                }, ReactUtils$OptolithClient.optionR((function (str) {
                        return React.createElement("p", {
                                    className: "description"
                                  }, ReactUtils$OptolithClient.s(str));
                      }), description), Ley_List$OptolithClient.listToArray(Curry._2(Ley_List$OptolithClient.map, (function (button) {
                            return React.createElement(ActionSheet$Button, {
                                        label: button.label,
                                        value: button.value,
                                        style: button.style,
                                        disabled: button.disabled,
                                        onClick: onClick
                                      });
                          }), buttons))), React.createElement("footer", undefined, React.createElement("button", {
                      className: "primary",
                      type: "button",
                      onClick: onClose
                    }, ReactUtils$OptolithClient.s(cancelLabel))));
}

var make = ActionSheet;

exports.Button = Button;
exports.make = make;
/* react Not a pure module */
