// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ClassNames$OptolithClient = require("../../../Utilities/ClassNames.bs.js");

function Button(Props) {
  var className = Props.className;
  var disabledOpt = Props.disabled;
  var label = Props.label;
  var onClick = Props.onClick;
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  return React.createElement("button", {
              className: ClassNames$OptolithClient.fold({
                    hd: className,
                    tl: {
                      hd: ClassNames$OptolithClient.cond("disabled", disabled),
                      tl: /* [] */0
                    }
                  }),
              onClick: onClick
            }, label);
}

var make = Button;

exports.make = make;
/* react Not a pure module */
