// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ClassNames$OptolithClient from "../../../Utilities/ClassNames.bs.js";
import * as Ley_Option$OptolithClient from "../../../Data/Ley_Option.bs.js";
import * as ReactUtils$OptolithClient from "../../../Utilities/ReactUtils.bs.js";

function Overlay(Props) {
  var baseClassName = Props.baseClassName;
  var className = Props.className;
  var children = Props.children;
  var isOpen = Props.isOpen;
  var onBackdrop = Props.onBackdrop;
  var backdropRef = React.useRef(null);
  var handleBackdropClick = React.useCallback((function ($$event) {
          Curry._2(Ley_Option$OptolithClient.Infix.$less$amp$great, Caml_option.nullable_to_opt(backdropRef.current), (function (currentRef) {
                  if (!currentRef.contains(ReactUtils$OptolithClient.eventTargetToDom($$event.target))) {
                    return Curry._1(onBackdrop, $$event);
                  }
                  
                }));
          
        }), [onBackdrop]);
  if (isOpen) {
    return ReactDom.createPortal(React.createElement("div", {
                    ref: backdropRef,
                    className: ClassNames$OptolithClient.fold({
                          hd: Curry._1(Ley_Option$OptolithClient.$$return, baseClassName + "-backdrop"),
                          tl: {
                            hd: className,
                            tl: /* [] */0
                          }
                        }),
                    onClick: handleBackdropClick
                  }, React.createElement("div", {
                        "aria-modal": true,
                        className: baseClassName,
                        role: "dialog"
                      }, children)), document.body);
  } else {
    return null;
  }
}

var make = Overlay;

export {
  make ,
  
}
/* react Not a pure module */
