// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ClassNames$OptolithClient = require("../../../Utilities/ClassNames.bs.js");

function Switch(Props) {
  var name = Props.name;
  var checked = Props.checked;
  var disabled = Props.disabled;
  var onChange = Props.onChange;
  return React.createElement("div", {
              className: ClassNames$OptolithClient.fold({
                    hd: "switch",
                    tl: {
                      hd: ClassNames$OptolithClient.cond("disabled", disabled),
                      tl: /* [] */0
                    }
                  })
            }, React.createElement("input", {
                  id: name,
                  checked: checked,
                  disabled: disabled,
                  name: name,
                  type: "checkbox",
                  onChange: onChange
                }), React.createElement("div", {
                  className: "switch-border"
                }, React.createElement("div", {
                      className: "switch-handle"
                    })));
}

var make = Switch;

exports.make = make;
/* react Not a pure module */
