// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var IC$OptolithClient = require("./IC.bs.js");
var Decoder$OptolithClient = require("../Utilities/Decoder.bs.js");
var Erratum$OptolithClient = require("../Sources/Erratum.bs.js");
var JsonStrict$OptolithClient = require("../Misc/JsonStrict.bs.js");
var Ley_IntMap$OptolithClient = require("../Data/Ley_IntMap.bs.js");
var Ley_Option$OptolithClient = require("../Data/Ley_Option.bs.js");
var SkillCheck$OptolithClient = require("./SkillCheck.bs.js");
var PublicationRef$OptolithClient = require("../Sources/PublicationRef.bs.js");
var TranslationMap$OptolithClient = require("../Misc/TranslationMap.bs.js");
var ActivatableSkill$OptolithClient = require("./ActivatableSkill.bs.js");

function t(json) {
  return JsonStrict$OptolithClient.field("name", JsonStrict$OptolithClient.string, json);
}

var MusicTraditionTranslation = {
  t: t
};

var MusicTraditionTranslationMap = TranslationMap$OptolithClient.Make(MusicTraditionTranslation);

function musicTraditionMultilingual(json) {
  return {
          id: JsonStrict$OptolithClient.field("id", JsonStrict$OptolithClient.$$int, json),
          translations: JsonStrict$OptolithClient.field("translations", MusicTraditionTranslationMap.Decode.t, json)
        };
}

function musicTraditionMultilingualAssoc(json) {
  var x = musicTraditionMultilingual(json);
  return [
          x.id,
          x
        ];
}

function t$1(json) {
  return {
          name: JsonStrict$OptolithClient.field("name", JsonStrict$OptolithClient.string, json),
          effect: JsonStrict$OptolithClient.field("effect", JsonStrict$OptolithClient.string, json),
          duration: JsonStrict$OptolithClient.field("duration", ActivatableSkill$OptolithClient.MainParameter.decode, json),
          cost: JsonStrict$OptolithClient.field("cost", ActivatableSkill$OptolithClient.MainParameter.decode, json),
          errata: JsonStrict$OptolithClient.optionalField("errata", Erratum$OptolithClient.Decode.list, json)
        };
}

var Translation = {
  t: t$1
};

var TranslationMap = TranslationMap$OptolithClient.Make(Translation);

function multilingual(json) {
  return {
          id: JsonStrict$OptolithClient.field("id", JsonStrict$OptolithClient.$$int, json),
          check: JsonStrict$OptolithClient.field("check", SkillCheck$OptolithClient.Decode.t, json),
          musicTradition: Curry._1(Ley_IntMap$OptolithClient.fromList, JsonStrict$OptolithClient.field("musicTradition", (function (param) {
                      return JsonStrict$OptolithClient.list(musicTraditionMultilingualAssoc, param);
                    }), json)),
          property: JsonStrict$OptolithClient.field("property", JsonStrict$OptolithClient.$$int, json),
          ic: JsonStrict$OptolithClient.field("ic", IC$OptolithClient.Decode.t, json),
          src: JsonStrict$OptolithClient.field("src", PublicationRef$OptolithClient.Decode.multilingualList, json),
          translations: JsonStrict$OptolithClient.field("translations", TranslationMap.Decode.t, json)
        };
}

function t$2(langs, json) {
  var x = multilingual(json);
  return Curry._2(Ley_Option$OptolithClient.Infix.$less$amp$great, Curry._2(TranslationMap.Decode.getFromLanguageOrder, langs, x.translations), (function (translation) {
                return {
                        id: x.id,
                        name: translation.name,
                        check: x.check,
                        effect: translation.effect,
                        duration: ActivatableSkill$OptolithClient.MainParameter.make(false, translation.duration),
                        cost: ActivatableSkill$OptolithClient.MainParameter.make(false, translation.cost),
                        musicTraditions: Curry._2(Ley_IntMap$OptolithClient.mapMaybe, (function (musicTradition) {
                                return Curry._2(MusicTraditionTranslationMap.Decode.getFromLanguageOrder, langs, musicTradition.translations);
                              }), x.musicTradition),
                        property: x.property,
                        ic: x.ic,
                        src: PublicationRef$OptolithClient.Decode.resolveTranslationsList(langs, x.src),
                        errata: Ley_Option$OptolithClient.fromOption(/* [] */0, translation.errata)
                      };
              }));
}

function toAssoc(x) {
  return [
          x.id,
          x
        ];
}

function assoc(param, param$1) {
  return Decoder$OptolithClient.decodeAssoc(t$2, toAssoc, param, param$1);
}

var Dynamic = ActivatableSkill$OptolithClient.Dynamic;

var Static = {
  Decode: {
    assoc: assoc
  }
};

exports.Dynamic = Dynamic;
exports.Static = Static;
/* MusicTraditionTranslationMap Not a pure module */
