// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function getICMultiplier(ic) {
  if (ic === 5) {
    return 15;
  } else {
    return ic;
  }
}

exports.getICMultiplier = getICMultiplier;
/* No side effect */
