open IO.Infix

type t = {
  advanced_combat_special_abilities : string list;
  advanced_karma_special_abilities : string list;
  advanced_magical_special_abilities : string list;
  advantages : string list;
  ancestor_glyphs : string list;
  animal_shape_paths : string list;
  animal_shapes : string list;
  animal_shape_sizes : string list;
  animist_forces : string list;
  arcane_bard_traditions : string list;
  arcane_dancer_traditions : string list;
  armors : string list;
  armor_types : string list;
  aspects : string list;
  attire_enchantments : string list;
  attributes : string list;
  blessed_traditions : string list;
  blessings : string list;
  brawling_special_abilities : string list;
  brews : string list;
  cantrips : string list;
  ceremonial_item_special_abilities : string list;
  ceremonies : string list;
  chronikzauber : string list;
  combat_special_abilities : string list;
  combat_special_ability_groups : string list;
  combat_style_special_abilities : string list;
  combat_technique_groups : string list;
  command_special_abilities : string list;
  conditions : string list;
  core_rules : string list;
  cultures : string list;
  curricula : string list;
  curses : string list;
  dagger_rituals : string list;
  derived_characteristics : string list;
  disadvantages : string list;
  diseases : string list;
  domination_rituals : string list;
  elements : string list;
  elven_magical_songs : string list;
  equipment_packages : string list;
  erweiterte_talentsonderfertigkeiten : string list;
  experience_levels : string list;
  eye_colors : string list;
  familiar_special_abilities : string list;
  fate_point_special_abilities : string list;
  focus_rules : string list;
  general_special_abilities : string list;
  geodenrituale : string list;
  hair_colors : string list;
  instrument_enchantments : string list;
  item_groups : string list;
  items : string list;
  kappenzauber : string list;
  karma_special_abilities : string list;
  kesselzauber : string list;
  kugelzauber : string list;
  languages : string list;
  liturgical_chant_groups : string list;
  liturgical_chants : string list;
  liturgical_style_special_abilities : string list;
  lykanthropische_gaben : string list;
  magical_dances : string list;
  magical_melodies : string list;
  magical_special_abilities : string list;
  magical_traditions : string list;
  magic_style_special_abilities : string list;
  melee_combat_techniques : string list;
  optional_rules : string list;
  orb_enchantments : string list;
  pact_categories : string list;
  paktgeschenke : string list;
  patron_categories : string list;
  patrons : string list;
  poisons : string list;
  professions : string list;
  properties : string list;
  protective_warding_circle_special_abilities : string list;
  publications : string list;
  races : string list;
  ranged_combat_techniques : string list;
  reaches : string list;
  ringzauber : string list;
  rituals : string list;
  schalenzauber : string list;
  schelmenzauber : string list;
  scripts : string list;
  sermons : string list;
  sex_schicksalspunkte_sonderfertigkeiten : string list;
  sex_sonderfertigkeiten : string list;
  sichelrituale : string list;
  sikaryan_raub_sonderfertigkeiten : string list;
  skill_groups : string list;
  skills : string list;
  social_statuses : string list;
  special_ability_groups : string list;
  spell_groups : string list;
  spells : string list;
  spell_sword_enchantments : string list;
  spielzeugzauber : string list;
  staff_enchantments : string list;
  states : string list;
  subjects : string list;
  talentstilsonderfertigkeiten : string list;
  trade_secrets : string list;
  tribes : string list;
  ui : string list;
  vampirische_gaben : string list;
  visions : string list;
  waffenzauber : string list;
  wand_enchantments : string list;
  weapons : string list;
  zibiljarituale : string list;
}

let data_root = Node.Path.join [| "."; "src"; "Database"; "Data" |]

let readFilesOfEntryType dir =
  let create_path file_name = Node.Path.join [| data_root; dir; file_name |] in
  let read_file_name file_name = create_path file_name |> IO.readFile in
  Node.Path.join2 data_root dir
  |> Directory.getDirectoryContents |> IO.mapM read_file_name

let readDirectories ~onProgress dirs =
  let max = dirs |> Ley_List.length |> Js.Int.toFloat in
  dirs
  |> IO.imapM (fun i dir ->
         dir |> readFilesOfEntryType <&> fun res ->
         let () = onProgress ((Js.Int.toFloat i +. 1.) /. max) in
         res)

let dirs =
  [
    "AdvancedCombatSpecialAbilities";
    "AdvancedKarmaSpecialAbilities";
    "AdvancedMagicalSpecialAbilities";
    "Advantages";
    "AncestorGlyphs";
    "AnimalShapePaths";
    "AnimalShapes";
    "AnimalShapeSizes";
    "AnimistForces";
    "ArcaneBardTraditions";
    "ArcaneDancerTraditions";
    "Armors";
    "ArmorTypes";
    "Aspects";
    "AttireEnchantments";
    "Attributes";
    "BlessedTraditions";
    "Blessings";
    "BrawlingSpecialAbilities";
    "Brews";
    "Cantrips";
    "CeremonialItemSpecialAbilities";
    "Ceremonies";
    "Chronikzauber";
    "CombatSpecialAbilities";
    "CombatSpecialAbilityGroups";
    "CombatStyleSpecialAbilities";
    "CombatTechniqueGroups";
    "CommandSpecialAbilities";
    "Conditions";
    "CoreRules";
    "Cultures";
    "Curricula";
    "Curses";
    "DaggerRituals";
    "DerivedCharacteristics";
    "Disadvantages";
    "Diseases";
    "DominationRituals";
    "Elements";
    "ElvenMagicalSongs";
    "EquipmentPackages";
    "ErweiterteTalentsonderfertigkeiten";
    "ExperienceLevels";
    "EyeColors";
    "FamiliarSpecialAbilities";
    "FatePointSpecialAbilities";
    "FocusRules";
    "GeneralSpecialAbilities";
    "GeodeRituals";
    "HairColors";
    "InstrumentEnchantments";
    "ItemGroups";
    "Items";
    "Kappenzauber";
    "KarmaSpecialAbilities";
    "Kesselzauber";
    "Kugelzauber";
    "Languages";
    "LiturgicalChantGroups";
    "LiturgicalChants";
    "LiturgicalStyleSpecialAbilities";
    "LykanthropischeGaben";
    "MagicalDances";
    "MagicalMelodies";
    "MagicalSpecialAbilities";
    "MagicalTraditions";
    "MagicStyleSpecialAbilities";
    "MeleeCombatTechniques";
    "OptionalRules";
    "OrbEnchantments";
    "PactCategories";
    "Paktgeschenke";
    "PatronCategories";
    "Patrons";
    "Poisons";
    "Professions";
    "Properties";
    "ProtectiveWardingCircleSpecialAbilities";
    "Publications";
    "Races";
    "RangedCombatTechniques";
    "Reaches";
    "Ringzauber";
    "Rituals";
    "RogueSpells";
    "Schalenzauber";
    "Scripts";
    "Sermons";
    "SexSchicksalspunkteSonderfertigkeiten";
    "SexSonderfertigkeiten";
    "Sichelrituale";
    "SikaryanRaubSonderfertigkeiten";
    "SkillGroups";
    "Skills";
    "SocialStatuses";
    "SpecialAbilityGroups";
    "SpellGroups";
    "Spells";
    "SpellSwordEnchantments";
    "Spielzeugzauber";
    "StaffEnchantments";
    "States";
    "Subjects";
    "Talentstilsonderfertigkeiten";
    "TradeSecrets";
    "Tribes";
    "UI";
    "VampirischeGaben";
    "Visions";
    "Waffenzauber";
    "WandEnchantments";
    "Weapons";
    "ZibiljaRituals";
  ]

let readFiles ~onProgress =
  dirs |> readDirectories ~onProgress <&> function
  | [
      advanced_combat_special_abilities;
      advanced_karma_special_abilities;
      advanced_magical_special_abilities;
      advantages;
      ancestor_glyphs;
      animal_shape_paths;
      animal_shapes;
      animal_shape_sizes;
      animist_forces;
      arcane_bard_traditions;
      arcane_dancer_traditions;
      armors;
      armor_types;
      aspects;
      attire_enchantments;
      attributes;
      blessed_traditions;
      blessings;
      brawling_special_abilities;
      brews;
      cantrips;
      ceremonial_item_special_abilities;
      ceremonies;
      chronikzauber;
      combat_special_abilities;
      combat_special_ability_groups;
      combat_style_special_abilities;
      combat_technique_groups;
      command_special_abilities;
      conditions;
      core_rules;
      cultures;
      curricula;
      curses;
      dagger_rituals;
      derived_characteristics;
      disadvantages;
      diseases;
      domination_rituals;
      elements;
      elven_magical_songs;
      equipment_packages;
      erweiterte_talentsonderfertigkeiten;
      experience_levels;
      eye_colors;
      familiar_special_abilities;
      fate_point_special_abilities;
      focus_rules;
      general_special_abilities;
      geodenrituale;
      hair_colors;
      instrument_enchantments;
      item_groups;
      items;
      kappenzauber;
      karma_special_abilities;
      kesselzauber;
      kugelzauber;
      languages;
      liturgical_chant_groups;
      liturgical_chants;
      liturgical_style_special_abilities;
      lykanthropische_gaben;
      magical_dances;
      magical_melodies;
      magical_special_abilities;
      magical_traditions;
      magic_style_special_abilities;
      melee_combat_techniques;
      optional_rules;
      orb_enchantments;
      pact_categories;
      paktgeschenke;
      patron_categories;
      patrons;
      poisons;
      professions;
      properties;
      protective_warding_circle_special_abilities;
      publications;
      races;
      ranged_combat_techniques;
      reaches;
      ringzauber;
      rituals;
      schelmenzauber;
      schalenzauber;
      scripts;
      sermons;
      sex_schicksalspunkte_sonderfertigkeiten;
      sex_sonderfertigkeiten;
      sichelrituale;
      sikaryan_raub_sonderfertigkeiten;
      skill_groups;
      skills;
      social_statuses;
      special_ability_groups;
      spell_groups;
      spells;
      spell_sword_enchantments;
      spielzeugzauber;
      staff_enchantments;
      states;
      subjects;
      talentstilsonderfertigkeiten;
      trade_secrets;
      tribes;
      ui;
      vampirische_gaben;
      visions;
      waffenzauber;
      wand_enchantments;
      weapons;
      zibiljarituale;
    ] ->
      {
        advanced_combat_special_abilities;
        advanced_karma_special_abilities;
        advanced_magical_special_abilities;
        advantages;
        ancestor_glyphs;
        animal_shape_paths;
        animal_shapes;
        animal_shape_sizes;
        animist_forces;
        arcane_bard_traditions;
        arcane_dancer_traditions;
        armors;
        armor_types;
        aspects;
        attire_enchantments;
        attributes;
        blessed_traditions;
        blessings;
        brawling_special_abilities;
        brews;
        cantrips;
        ceremonial_item_special_abilities;
        ceremonies;
        chronikzauber;
        combat_special_abilities;
        combat_special_ability_groups;
        combat_style_special_abilities;
        combat_technique_groups;
        command_special_abilities;
        conditions;
        core_rules;
        cultures;
        curricula;
        curses;
        dagger_rituals;
        derived_characteristics;
        disadvantages;
        diseases;
        domination_rituals;
        elements;
        elven_magical_songs;
        equipment_packages;
        erweiterte_talentsonderfertigkeiten;
        experience_levels;
        eye_colors;
        familiar_special_abilities;
        fate_point_special_abilities;
        focus_rules;
        general_special_abilities;
        geodenrituale;
        hair_colors;
        instrument_enchantments;
        item_groups;
        items;
        kappenzauber;
        karma_special_abilities;
        kesselzauber;
        kugelzauber;
        languages;
        liturgical_chant_groups;
        liturgical_chants;
        liturgical_style_special_abilities;
        lykanthropische_gaben;
        magical_dances;
        magical_melodies;
        magical_special_abilities;
        magical_traditions;
        magic_style_special_abilities;
        melee_combat_techniques;
        optional_rules;
        orb_enchantments;
        pact_categories;
        paktgeschenke;
        patron_categories;
        patrons;
        poisons;
        professions;
        properties;
        protective_warding_circle_special_abilities;
        publications;
        races;
        ranged_combat_techniques;
        reaches;
        ringzauber;
        rituals;
        schelmenzauber;
        schalenzauber;
        scripts;
        sermons;
        sex_schicksalspunkte_sonderfertigkeiten;
        sex_sonderfertigkeiten;
        sichelrituale;
        sikaryan_raub_sonderfertigkeiten;
        skill_groups;
        skills;
        social_statuses;
        special_ability_groups;
        spell_groups;
        spells;
        spell_sword_enchantments;
        spielzeugzauber;
        staff_enchantments;
        states;
        subjects;
        talentstilsonderfertigkeiten;
        trade_secrets;
        tribes;
        ui;
        vampirische_gaben;
        visions;
        waffenzauber;
        wand_enchantments;
        weapons;
        zibiljarituale;
      }
  | xs ->
      failwith
        ( "Unexpected length of directories: "
        ^ Ley_Int.show (Ley_List.length xs) )
