// Generated by ReScript, PLEASE EDIT WITH CARE


function send(emitter, message) {
  emitter.webContents.send("messageFromMain", message);
  
}

function addListener(emitter, callback) {
  emitter.addListener("messageFromMain", callback);
  
}

function reply(emitter, message) {
  emitter.sender.send("messageFromRenderer", message);
  
}

var FromMain = {
  send: send,
  addListener: addListener,
  reply: reply
};

function send$1(emitter, message) {
  emitter.send("messageFromRenderer", message);
  
}

function addListener$1(emitter, callback) {
  emitter.addListener("messageFromRenderer", callback);
  
}

function reply$1(emitter, message) {
  emitter.sender.send("messageFromMain", message);
  
}

var FromRenderer = {
  send: send$1,
  addListener: addListener$1,
  reply: reply$1
};

export {
  FromMain ,
  FromRenderer ,
  
}
/* No side effect */
