// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Activatable_Active_Name$OptolithClient = require("./Activatable_Active_Name.bs.js");
var Activatable_Active_Validation$OptolithClient = require("./Activatable_Active_Validation.bs.js");
var Activatable_Active_AdventurePointValue$OptolithClient = require("./Activatable_Active_AdventurePointValue.bs.js");

function getActive(isEntryToAdd, addLevelToName, cache, staticData, hero, staticEntry, heroEntry, singleEntry) {
  var naming = Activatable_Active_Name$OptolithClient.getName(addLevelToName, staticData, staticEntry, singleEntry);
  var validation = Activatable_Active_Validation$OptolithClient.isRemovalOrModificationValid(cache, staticData, hero, staticEntry, heroEntry, singleEntry);
  var match = Activatable_Active_AdventurePointValue$OptolithClient.getApValueDifferenceOnChange(isEntryToAdd, cache.automaticAdvantages, staticData, hero, staticEntry, heroEntry, singleEntry);
  return {
          naming: naming,
          active: singleEntry,
          apValue: match.apValue,
          isAutomatic: match.isAutomatic,
          validation: validation,
          staticEntry: staticEntry,
          heroEntry: heroEntry
        };
}

exports.getActive = getActive;
/* Activatable_Active_Name-OptolithClient Not a pure module */
