// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ley_List$OptolithClient = require("../Data/Ley_List.bs.js");

function singleToSingleWithId(x, index, s) {
  return {
          id: x.id,
          index: index,
          options: s.options,
          level: s.level,
          customCost: s.customCost
        };
}

function heroEntryToSingles(x) {
  return Ley_List$OptolithClient.Index.imap((function (param, param$1) {
                return singleToSingleWithId(x, param, param$1);
              }), x.active);
}

function singleWithIdToSingle(s) {
  return {
          options: s.options,
          level: s.level,
          customCost: s.customCost
        };
}

function activatableOptionToSelectOptionId(id) {
  if (id.TAG) {
    return ;
  } else {
    return id._0;
  }
}

exports.heroEntryToSingles = heroEntryToSingles;
exports.singleToSingleWithId = singleToSingleWithId;
exports.activatableOptionToSelectOptionId = activatableOptionToSelectOptionId;
exports.singleWithIdToSingle = singleWithIdToSingle;
/* Ley_List-OptolithClient Not a pure module */
