// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as JsonStrict$OptolithClient from "../Misc/JsonStrict.bs.js";
import * as Ley_Option$OptolithClient from "../Data/Ley_Option.bs.js";

function t(json) {
  return {
          date: Json_decode.field("date", Json_decode.date, json),
          description: Json_decode.field("description", Json_decode.string, json)
        };
}

function list(json) {
  return Ley_Option$OptolithClient.fromOption(/* [] */0, JsonStrict$OptolithClient.maybe((function (param) {
                    return Json_decode.list(t, param);
                  }), json));
}

var Decode = {
  list: list
};

export {
  Decode ,
  
}
/* Ley_Option-OptolithClient Not a pure module */
