// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Ley_List$OptolithClient from "../Data/Ley_List.bs.js";
import * as Ley_StrMap$OptolithClient from "../Data/Ley_StrMap.bs.js";

function t(json) {
  return {
          id: Json_decode.field("id", Json_decode.string, json),
          name: Json_decode.field("name", Json_decode.string, json),
          short: Json_decode.field("short", Json_decode.string, json),
          isCore: Json_decode.field("isCore", Json_decode.bool, json),
          isAdultContent: Json_decode.field("isAdultContent", Json_decode.bool, json)
        };
}

function all(yamlData) {
  return Curry._1(Ley_StrMap$OptolithClient.fromList, Ley_List$OptolithClient.map((function (x) {
                    return [
                            x.id,
                            x
                          ];
                  }), Json_decode.list(t, yamlData.booksL10n)));
}

var Decode = {
  t: t,
  all: all
};

export {
  Decode ,
  
}
/* Ley_StrMap-OptolithClient Not a pure module */
