// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Url = require("url");
var Path = require("path");
var Curry = require("bs-platform/lib/js/curry.js");
var Semver = require("semver");
var Electron = require("electron");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var IO$OptolithClient = require("./Data/IO.bs.js");
var Ipc$OptolithClient = require("./Init/Ipc.bs.js");
var Init$OptolithClient = require("./Init/Init.bs.js");
var ElectronWindowState = require("electron-window-state").default;
var Electron$OptolithClient = require("./ExternalBindings/Electron.bs.js");
var Ley_Option$OptolithClient = require("./Data/Ley_Option.bs.js");
var AutoUpdates$OptolithClient = require("./Init/AutoUpdates.bs.js");
var ElectronDevtoolsInstaller = require("electron-devtools-installer");
var ElectronDevtoolsInstaller$1 = require("electron-devtools-installer").default;

Electron.app.setAppUserModelId("lukasobermann.optolith");

function setDerivedUserDataPath(param) {
  console.log("main: Set user data path ...");
  var isPrerelease = Ley_Option$OptolithClient.isNone(Caml_option.null_to_opt(Semver.prerelease(Electron.app.getVersion())));
  var userDataPath = Path.join(Electron.app.getPath("appData"), isPrerelease ? "Optolith Insider" : "Optolith");
  return Curry._2(IO$OptolithClient.Infix.$less$amp$great, Curry._2(IO$OptolithClient.Infix.$great$great$eq, IO$OptolithClient.existsFile(userDataPath), (function (exists) {
                    if (exists) {
                      return Curry._1(IO$OptolithClient.$$return, undefined);
                    } else {
                      return IO$OptolithClient.mkdir(userDataPath);
                    }
                  })), (function (param) {
                Electron.app.setPath("userData", userDataPath);
                console.log("main: User data path set to \"" + (userDataPath + "\""));
                
              }));
}

function installDevelopmentExtensions(param) {
  console.log("main: Install extensions ...");
  return Curry._2(IO$OptolithClient.Infix.$less$amp$great, ElectronDevtoolsInstaller$1([
                  ElectronDevtoolsInstaller.REACT_DEVELOPER_TOOLS,
                  ElectronDevtoolsInstaller.REDUX_DEVTOOLS
                ]), (function (installedExtensions) {
                console.log("main: Installed extensions: " + installedExtensions);
                
              }));
}

function createWindow(param) {
  console.log("main: Create Window ...");
  console.log("main (window): Initialize window state keeper");
  var mainWindowState = ElectronWindowState({
        defaultHeight: 720,
        defaultWidth: 1280,
        file: "window.json"
      });
  console.log("main (window): Initialize browser window");
  var mainWindow = new Electron.BrowserWindow({
        width: mainWindowState.width,
        height: mainWindowState.height,
        x: mainWindowState.x,
        y: mainWindowState.y,
        minWidth: 1280,
        minHeight: 720,
        center: true,
        resizable: true,
        title: "Optolith",
        icon: Path.join(Electron.app.getAppPath(), "src", "icon.png"),
        show: false,
        frame: false,
        acceptFirstMouse: true,
        backgroundColor: "#111111",
        webPreferences: {
          nodeIntegration: true,
          enableRemoteModule: true
        }
      });
  console.log("main (window): Manage browser window with state keeper");
  mainWindowState.manage(mainWindow);
  console.log("main (window): Load url");
  return Curry._2(IO$OptolithClient.Infix.$less$amp$great, mainWindow.loadURL(Url.format({
                      pathname: Path.join(__dirname, "index.html"),
                      protocol: "file:",
                      slashes: true
                    })), (function (param) {
                mainWindow.webContents.openDevTools();
                console.log("main (window): Show window");
                mainWindow.show();
                if (mainWindowState.isMaximized) {
                  console.log("main (window): Maximize window ...");
                  mainWindow.maximize();
                }
                return mainWindow;
              }));
}

function initializeData(mainWindow) {
  console.time("parseStaticData");
  return Curry._2(IO$OptolithClient.Infix.$less$amp$great, Init$OptolithClient.getInitialData((function (supportedLanguages, localeOrder, config, uiMessages) {
                    return Ipc$OptolithClient.FromMain.send(mainWindow, {
                                TAG: /* InitMinimal */0,
                                _0: supportedLanguages,
                                _1: localeOrder,
                                _2: config,
                                _3: uiMessages
                              });
                  }), Path.join(__dirname, "initWorker.js"), (function (progress) {
                    return Ipc$OptolithClient.FromMain.send(mainWindow, {
                                TAG: /* InitProgress */1,
                                _0: progress
                              });
                  })), (function (staticData) {
                console.timeEnd("parseStaticData");
                return Ipc$OptolithClient.FromMain.send(mainWindow, {
                            TAG: /* InitDone */2,
                            _0: staticData
                          });
              }));
}

function main(param) {
  Curry._2(IO$OptolithClient.Infix.$great$great$eq, Curry._2(IO$OptolithClient.Infix.$great$great$eq, Curry._2(IO$OptolithClient.Infix.$great$great$eq, setDerivedUserDataPath(undefined), installDevelopmentExtensions), createWindow), (function (mainWindow) {
            return Curry._2(IO$OptolithClient.Infix.$less$amp$great, initializeData(mainWindow), (function (param) {
                          AutoUpdates$OptolithClient.listenAndRun(mainWindow);
                          return Curry._1(Electron$OptolithClient.App.on, {
                                      NAME: "windowAllClosed",
                                      VAL: (function (param) {
                                          Electron.app.quit();
                                          
                                        })
                                    });
                        }));
          })).catch(function (err) {
        console.error(err);
        return Curry._1(IO$OptolithClient.$$return, undefined);
      });
  
}

Curry._1(Electron$OptolithClient.App.on, {
      NAME: "ready",
      VAL: main
    });

exports.setDerivedUserDataPath = setDerivedUserDataPath;
exports.installDevelopmentExtensions = installDevelopmentExtensions;
exports.createWindow = createWindow;
exports.initializeData = initializeData;
exports.main = main;
/*  Not a pure module */
