// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Ley_IntMap$OptolithClient from "../Data/Ley_IntMap.bs.js";
import * as Ley_Option$OptolithClient from "../Data/Ley_Option.bs.js";

function hasFrequencyRating(currentEntryRating, ratingMap, id) {
  return Ley_Option$OptolithClient.Foldable.elem(currentEntryRating, Curry._2(Ley_IntMap$OptolithClient.lookup, id, ratingMap));
}

function isCommon(param, param$1) {
  return hasFrequencyRating(/* Common */0, param, param$1);
}

function isUncommon(param, param$1) {
  return hasFrequencyRating(/* Uncommon */1, param, param$1);
}

export {
  hasFrequencyRating ,
  isCommon ,
  isUncommon ,
  
}
/* Ley_IntMap-OptolithClient Not a pure module */
