// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Ley_List$OptolithClient from "../Data/Ley_List.bs.js";

var Rules = {};

function empty(id) {
  return {
          id: id,
          active: /* [] */0,
          dependencies: /* [] */0
        };
}

function isUnused(x) {
  if (Curry._1(Ley_List$OptolithClient.$$null, x.active)) {
    return Curry._1(Ley_List$OptolithClient.$$null, x.dependencies);
  } else {
    return false;
  }
}

var Activatable = {
  empty: empty,
  isUnused: isUnused
};

var Energies = {};

var MagicalActions = {};

var Item = {};

var Pact = {};

var TransferUnfamiliar = {};

export {
  Rules ,
  Activatable ,
  Energies ,
  MagicalActions ,
  Item ,
  Pact ,
  TransferUnfamiliar ,
  
}
/* Ley_List-OptolithClient Not a pure module */
