import { Character } from "./character.ts"

/**
 * A base character that can be used for testing. It is meant to be extended
 * with the properties that are needed for the test.
 */
export const baseCharacter: Character = {
  id: "550e8400-e29b-11d4-a716-446655440000",
  version: undefined,
  name: "Alrik",
  dateCreated: "2023-10-13T14:15:50.267Z",
  dateLastModified: "2023-10-13T14:15:50.267Z",
  totalAdventurePoints: 1100,
  experienceLevelStartId: 3,
  isCharacterCreationFinished: false,
  race: {
    id: 1,
    variantId: 1,
    selectedAttributeAdjustmentId: 1,
  },
  culture: {
    id: 1,
    isCulturalPackageApplied: false,
  },
  profession: {
    id: 1,
    instanceId: 1,
  },
  rules: {
    includeAllPublications: false,
    includePublications: [],
    activeFocusRules: {},
    activeOptionalRules: {},
  },
  activeStates: {},
  personalData: {
    sex: { type: "Male" },
    socialStatus: {
      dependencies: [],
    },
  },
  advantages: {},
  disadvantages: {},
  specialAbilities: {
    advancedCombatSpecialAbilities: {},
    advancedKarmaSpecialAbilities: {},
    advancedMagicalSpecialAbilities: {},
    advancedSkillSpecialAbilities: {},
    ancestorGlyphs: {},
    arcaneOrbEnchantments: {},
    attireEnchantments: {},
    blessedTraditions: {},
    bowlEnchantments: {},
    brawlingSpecialAbilities: {},
    cauldronEnchantments: {},
    ceremonialItemSpecialAbilities: {},
    chronicleEnchantments: {},
    combatSpecialAbilities: {},
    combatStyleSpecialAbilities: {},
    commandSpecialAbilities: {},
    daggerRituals: {},
    familiarSpecialAbilities: {},
    fatePointSexSpecialAbilities: {},
    fatePointSpecialAbilities: {},
    foolsHatEnchantments: {},
    generalSpecialAbilities: {},
    instrumentEnchantments: {},
    karmaSpecialAbilities: {},
    krallenkettenzauber: {},
    liturgicalStyleSpecialAbilities: {},
    lycantropicGifts: {},
    magicalRunes: {},
    magicalSpecialAbilities: {},
    magicalTraditions: {},
    magicStyleSpecialAbilities: {},
    orbEnchantments: {},
    pactGifts: {},
    protectiveWardingCircleSpecialAbilities: {},
    ringEnchantments: {},
    sermons: {},
    sexSpecialAbilities: {},
    sickleRituals: {},
    sikaryanDrainSpecialAbilities: {},
    skillStyleSpecialAbilities: {},
    spellSwordEnchantments: {},
    staffEnchantments: {},
    toyEnchantments: {},
    trinkhornzauber: {},
    vampiricGifts: {},
    visions: {},
    wandEnchantments: {},
    weaponEnchantments: {},
  },
  attributes: {},
  derivedCharacteristics: {
    lifePoints: {
      purchased: 0,
      permanentlyLost: 0,
    },
    arcaneEnergy: {
      purchased: 0,
      permanentlyLost: 0,
      permanentlyLostBoughtBack: 0,
    },
    karmaPoints: {
      purchased: 0,
      permanentlyLost: 0,
      permanentlyLostBoughtBack: 0,
    },
  },
  skills: {},
  combatTechniques: {
    close: {},
    ranged: {},
  },
  cantrips: [],
  spells: {},
  rituals: {},
  magicalActions: {
    curses: {},
    elvenMagicalSongs: {},
    dominationRituals: {},
    magicalDances: {},
    magicalMelodies: {},
    jesterTricks: {},
    animistPowers: {},
    geodeRituals: {},
    zibiljaRituals: {},
  },
  blessings: [],
  liturgicalChants: {},
  ceremonies: {},
  magicalPrimaryAttributeDependencies: [],
  blessedPrimaryAttributeDependencies: [],
  // items: {}
  // hitZoneArmors: {}
  purse: {
    kreutzers: 0,
    halers: 0,
    silverthalers: 0,
    ducats: 0,
  },
  // creatures: {}
  // pact: {}
}
